import Image from 'next/image';import Link from 'next/link';import{motion}from'framer-motion';import{useRouter}from'next/router';import{serverSideTranslations}from'next-i18next/serverSideTranslations';import{ArrowRight,MessageCircle}from'lucide-react';import SEO from'../../components/SEO';
const W='https://wa.me/213549575512';
function R(t){return String(t).split(/(\*\*[^*]+\*\*)/g).map((p,i)=>p.startsWith('**')&&p.endsWith('**')?<span key={i} className="font-normal text-white border-b border-white/30">{p.slice(2,-2)}</span>:<span key={i}>{p}</span>);}
const f={hidden:{opacity:0,y:24},show:{opacity:1,y:0,transition:{duration:0.6,ease:[0.22,1,0.36,1]}}};
const st={hidden:{opacity:0},show:{opacity:1,transition:{staggerChildren:0.08,delayChildren:0.05}}};

const C={
  fr:{kind:'Guide bancaire',title:"Développement logiciel bancaire — gestion cash, systèmes de paiement et core banking sur mesure.",
    dek:"Comment construire un système de gestion cash bancaire qui tient en production. Architecture, intégrations SWIFT et SATIM, conformité Banque Centrale, et ce qui sépare un logiciel bancaire d'un ERP déguisé.",
    publishedAt:'Avril 2026',readTime:'14 min de lecture',author:'Symloop',
    intro:[
      "Si vous êtes DSI d'une banque, directeur IT d'un établissement de paiement, ou CTO d'une fintech au **Maghreb ou en Afrique**, vous avez probablement découvert que **les solutions bancaires « prêtes à l'emploi » ne gèrent pas votre réalité**. Le cash management, les paiements interbancaires, la réconciliation SWIFT, les spécificités de la Banque Centrale — tout cela nécessite du sur mesure.",
      "Ce guide n'est pas un argumentaire commercial. C'est un **guide technique écrit par des ingénieurs qui ont livré des systèmes bancaires en production** — pour des banques en Algérie, au Maghreb et en MENA. Voici ce que coûte réellement un logiciel bancaire sur mesure, ce qu'il inclut, et les erreurs qui tuent 80% des projets bancaires IT.",
    ],
    sections:[
      {heading:'Pourquoi les banques ont besoin de logiciel sur mesure',body:[
        "**Les solutions bancaires packagées** (Temenos, Finastra, Sopra Banking) coûtent entre **$500K et $5M en licence** — avant même l'implémentation. Pour une banque régionale au Maghreb ou une fintech en croissance, c'est souvent **2 à 3 ans de budget IT consommés sur la licence seule**.",
        "Le sur mesure devient le bon choix quand : **votre core banking est un système legacy des années 2000** que personne ne peut modifier, quand **la réglementation locale** (Banque d'Algérie, Banque Centrale de Tunisie, Bank Al-Maghrib) impose des formats et des flux que les solutions internationales ne supportent pas nativement, et quand **votre avantage compétitif** repose sur des processus que vous ne pouvez pas forcer dans un package standard.",
      ]},
      {heading:'Les 5 modules d\'un système de gestion cash bancaire',body:[
        "**Module 1 : Position de trésorerie en temps réel.** Vue consolidée de toutes les positions cash sur tous les comptes, toutes les devises, tous les correspondants bancaires. Mise à jour en temps réel via flux SWIFT MT940/MT942 et intégrations API avec les systèmes de compensation locaux.",
        "**Module 2 : Cash forecasting.** Prévision des flux de trésorerie sur 7, 30 et 90 jours basée sur l'historique transactionnel, les engagements futurs et les patterns saisonniers. **Un modèle ML entraîné sur les données locales** bat les prévisions Excel de 30 à 50% en précision.",
        "**Module 3 : Réconciliation automatique.** Matching automatique des transactions SWIFT entrantes/sortantes avec les écritures comptables internes. **Un système IA de réconciliation matche 92 à 97% des transactions automatiquement** — le reste est escaladé pour revue manuelle avec le contexte pré-rempli.",
        "**Module 4 : Gestion des paiements interbancaires.** Initiation, validation, et suivi des virements interbancaires via les systèmes de compensation nationaux (ATCI en Algérie, SIBTEL en Tunisie). Double validation, audit trail complet, conformité anti-blanchiment.",
        "**Module 5 : Reporting réglementaire.** Génération automatique des rapports requis par la Banque Centrale — situations de trésorerie, déclarations de change, reporting prudentiel. **Le module qui sauve le plus de temps humain** : ce que 3 personnes font en 5 jours, le système le génère en 5 minutes.",
      ]},
      {heading:'Architecture technique — ce qui tient en production bancaire',body:[
        "Un système bancaire en production n'est pas une app web avec une base de données. C'est une **architecture distribuée avec des exigences de fiabilité, d'audit et de sécurité** que 90% des développeurs n'ont jamais rencontrées.",
        "**Base de données : PostgreSQL avec réplication synchrone.** Pas de MongoDB, pas de Firebase. Les données financières nécessitent des **transactions ACID, un audit trail immuable, et une capacité de point-in-time recovery**. Chaque écriture est répliquée sur au moins 2 nœuds avant confirmation.",
        "**Messaging : Apache Kafka pour les événements transactionnels.** Chaque transaction est un événement immutable dans un log distribué. Permet le replay, l'audit, et l'intégration asynchrone avec les systèmes externes sans perte de données.",
        "**API : gRPC entre les services internes, REST pour les interfaces.** Les systèmes bancaires traitent des **milliers de transactions par seconde** — REST est trop lent pour la communication inter-services. gRPC avec Protocol Buffers offre 5 à 10x les performances.",
        "**Sécurité : chiffrement bout en bout, HSM pour les clés, zero-trust network.** Les clés cryptographiques ne sont jamais en mémoire sur un serveur applicatif — elles vivent dans un **Hardware Security Module (HSM)** certifié FIPS 140-2.",
      ]},
      {heading:'Conformité — ce que la Banque Centrale exige',body:[
        "**En Algérie :** la Banque d'Algérie impose des reporting mensuels sur les positions de change, la situation de trésorerie, et les engagements interbancaires. Le système doit générer ces rapports **dans le format exact prescrit** — pas un CSV générique, le template officiel.",
        "**Au Maroc :** Bank Al-Maghrib exige la conformité aux normes Bâle III, le reporting COREP/FINREP, et l'intégration avec le Système Interbancaire Marocain de Télécompensation (SIMT).",
        "**En Tunisie :** la Banque Centrale de Tunisie impose des déclarations quotidiennes de change et un reporting prudentiel mensuel via le système SIBTEL.",
        "**Pour les fintechs :** les établissements de paiement sous licence doivent générer des rapports d'activité trimestriels incluant les volumes de transactions, les taux de fraude, et les indicateurs KYC/AML. **Un système qui n'automatise pas ce reporting est un système qui vous coûte 2 employés à temps plein juste pour la conformité.**",
      ]},
      {heading:'Coût réel et timeline',body:[
        "**Système de gestion cash complet (5 modules) :** 15 à 50 millions de DA selon la complexité des intégrations. **Timeline : 6 à 12 mois.** Le module de réconciliation seul peut être livré en 3 mois pour un quick win.",
        "**Module de reporting réglementaire seul :** 3 à 8 millions de DA. **Timeline : 2 à 4 mois.** C'est souvent le premier module livré parce que le ROI est immédiat (remplacement de 3 à 5 jours de travail manuel par mois).",
        "**Intégration SWIFT :** 2 à 5 millions de DA supplémentaires. Nécessite une **certification SWIFT** et des tests avec le réseau de correspondants bancaires.",
        "**Comparé à Temenos ou Finastra :** un système sur mesure coûte **5 à 10x moins en licence** (pas de licence, le code vous appartient) et **2 à 3x moins en implémentation** parce que nous ne customisons pas un package — nous construisons exactement ce dont vous avez besoin.",
      ]},
      {heading:'Pourquoi nous — et pas un intégrateur Temenos',body:[
        "Nous ne sommes pas un revendeur de solution packagée. Nous sommes un **atelier d'ingénierie qui construit des systèmes bancaires de zéro**. Le code vous appartient dès le jour 1. Pas de licence annuelle. Pas de vendor lock-in.",
        "Nous livrons depuis **Alger** avec une présence locale, une facturation en dinars, et une connaissance directe des exigences réglementaires maghrébines. Nous parlons **français, arabe et anglais** — les trois langues du banking au Maghreb et en MENA.",
        "Nos ingénieurs ont travaillé sur des systèmes traitant **des millions de transactions par mois**. Pas des prototypes. Des systèmes en production depuis 3 à 7 ans.",
      ]},
    ],
    pullQuote1:"Un système de gestion cash bancaire n'est pas une app web avec une base de données. C'est une architecture distribuée avec des exigences que 90% des développeurs n'ont jamais rencontrées.",
    pullQuote2:"Un système sur mesure coûte 5 à 10x moins en licence que Temenos — et le code vous appartient dès le jour 1.",
    cta:{eyebrow:'Parlez à un ingénieur bancaire',title:"Vous construisez ou modernisez un système bancaire ? Décrivez votre projet en 5 minutes."},
    related:{insights:[{key:'erp',name:"ERP sur mesure pour PME — au-delà d'Odoo"},{key:'ai',name:"Automatisation IA dans l'entreprise algérienne"}],services:[{key:'software-engineering',name:'Ingénierie logicielle'},{key:'ai',name:'Intelligence Artificielle'}]},
  },
  en:{kind:'Banking guide',title:'Banking software development — cash management, payment systems, and custom core banking.',
    dek:'How to build a banking cash management system that holds in production. Architecture, SWIFT and SATIM integrations, Central Bank compliance, and what separates banking software from a disguised ERP.',
    publishedAt:'April 2026',readTime:'14 min read',author:'Symloop',
    intro:["If you are the CIO of a bank, IT director of a payment institution, or CTO of a fintech in **the Maghreb or Africa**, you have probably discovered that **off-the-shelf banking solutions don't handle your reality**. Cash management, interbank payments, SWIFT reconciliation, Central Bank specifics — all of this requires custom.","This guide is written by engineers who have **shipped banking systems in production** — for banks in Algeria, the Maghreb and MENA."],
    sections:[
      {heading:'Why banks need custom software',body:["**Packaged banking solutions** (Temenos, Finastra, Sopra Banking) cost **$500K to $5M in licensing** — before implementation. For a regional Maghreb bank or a growing fintech, that is often **2-3 years of IT budget consumed on licensing alone**.","Custom becomes the right choice when: your **core banking is a 2000s legacy** nobody can modify, when **local regulation** imposes formats that international solutions don't support natively, and when **your competitive advantage** relies on processes you cannot force into a standard package."]},
      {heading:'The 5 modules of a banking cash management system',body:["**Module 1: Real-time treasury position.** Consolidated view across all accounts, currencies, correspondent banks. Real-time via SWIFT MT940/MT942 and local clearing system APIs.","**Module 2: Cash forecasting.** ML model trained on local data **beats Excel forecasts by 30-50%** in accuracy.","**Module 3: Automatic reconciliation.** AI matching system **auto-reconciles 92-97% of transactions**. Rest escalated for manual review with pre-filled context.","**Module 4: Interbank payment management.** Initiation, validation, tracking via national clearing systems. Dual validation, full audit trail, AML compliance.","**Module 5: Regulatory reporting.** Auto-generates Central Bank reports. **What 3 people do in 5 days, the system generates in 5 minutes.**"]},
      {heading:'Technical architecture — what holds in banking production',body:["**Database: PostgreSQL with synchronous replication.** Financial data requires ACID transactions, immutable audit trail, and point-in-time recovery.","**Messaging: Apache Kafka for transaction events.** Every transaction is an immutable event. Enables replay, audit, and async integration.","**API: gRPC between internal services, REST for interfaces.** Banking systems process **thousands of transactions per second** — gRPC offers 5-10x performance over REST.","**Security: end-to-end encryption, HSM for keys, zero-trust.** Cryptographic keys live in **FIPS 140-2 certified HSM**, never in application memory."]},
      {heading:'Compliance — what the Central Bank requires',body:["**Algeria:** Bank of Algeria mandates monthly reporting on FX positions, treasury situation, interbank commitments.","**Morocco:** Bank Al-Maghrib requires Basel III compliance, COREP/FINREP reporting, SIMT integration.","**Tunisia:** Central Bank of Tunisia mandates daily FX declarations and monthly prudential reporting via SIBTEL.","**For fintechs:** quarterly activity reports including transaction volumes, fraud rates, KYC/AML indicators."]},
      {heading:'Real cost and timeline',body:["**Complete cash management (5 modules):** 15-50M DZD. **Timeline: 6-12 months.**","**Regulatory reporting module alone:** 3-8M DZD. **Timeline: 2-4 months.** Often first delivered for immediate ROI.","**SWIFT integration:** 2-5M DZD additional. Requires SWIFT certification.","**Compared to Temenos/Finastra:** custom costs **5-10x less in licensing** (no license, code is yours) and **2-3x less in implementation**."]},
      {heading:'Why us — and not a Temenos integrator',body:["We are not a packaged solution reseller. We are an **engineering workshop that builds banking systems from scratch**. Code is yours from day 1. No annual license. No vendor lock-in.","We deliver from **Algiers** with local presence, dinar invoicing, and direct knowledge of Maghreb regulatory requirements. We speak **French, Arabic and English** — the three languages of Maghreb and MENA banking."]},
    ],
    pullQuote1:"A banking cash management system is not a web app with a database. It is a distributed architecture with requirements 90% of developers have never encountered.",
    pullQuote2:"Custom costs 5-10x less in licensing than Temenos — and the code is yours from day 1.",
    cta:{eyebrow:'Talk to a banking engineer',title:"Building or modernizing a banking system? Describe your project in 5 minutes."},
    related:{insights:[{key:'erp',name:'Custom ERP for SMEs — beyond Odoo'},{key:'ai',name:'AI automation in Algerian business'}],services:[{key:'software-engineering',name:'Software Engineering'},{key:'ai',name:'Artificial Intelligence'}]},
  },
  ar:{kind:'دليل مصرفي',title:'تطوير البرمجيات المصرفية — إدارة النقد وأنظمة الدفع والخدمات المصرفية الأساسية المخصصة.',
    dek:'كيف تبني نظام إدارة نقد مصرفي يصمد في الإنتاج. الهندسة، تكاملات SWIFT وSATIM، امتثال البنك المركزي.',
    publishedAt:'أبريل 2026',readTime:'14 دقيقة قراءة',author:'سيملوب',
    intro:['إذا كنت مدير تكنولوجيا في بنك أو CTO في شركة فينتك في **المغرب العربي أو أفريقيا**، فقد اكتشفت على الأرجح أن **الحلول المصرفية الجاهزة لا تتعامل مع واقعك**. إدارة النقد، المدفوعات بين البنوك، تسوية SWIFT — كل هذا يحتاج إلى حل مخصص.'],
    sections:[
      {heading:'لماذا تحتاج البنوك إلى برمجيات مخصصة',body:['**الحلول المصرفية الجاهزة** (Temenos، Finastra) تكلف **$500K إلى $5M في الترخيص** — قبل التطبيق. المخصص يصبح الخيار الصحيح عندما: **نظامك القديم من العقد الأول** لا يمكن لأحد تعديله، و**التنظيم المحلي** يفرض صيغاً لا تدعمها الحلول الدولية.']},
      {heading:'الوحدات الخمس لنظام إدارة النقد المصرفي',body:['**الوحدة 1: وضع الخزينة في الوقت الفعلي.** رؤية موحدة عبر جميع الحسابات والعملات والبنوك المراسلة.','**الوحدة 2: التنبؤ بالنقد.** نموذج ML مدرَّب على البيانات المحلية **يتفوق على تنبؤات Excel بنسبة 30-50%**.','**الوحدة 3: التسوية التلقائية.** نظام IA يطابق تلقائياً **92-97% من المعاملات**.','**الوحدة 4: إدارة المدفوعات بين البنوك.** تحقق مزدوج، مسار تدقيق كامل، امتثال مكافحة غسيل الأموال.','**الوحدة 5: التقارير التنظيمية.** ما يفعله 3 أشخاص في 5 أيام، يولده النظام في 5 دقائق.']},
      {heading:'الهندسة التقنية',body:['**قاعدة البيانات: PostgreSQL مع نسخ متزامن.** البيانات المالية تتطلب معاملات ACID ومسار تدقيق غير قابل للتغيير.','**المراسلة: Apache Kafka للأحداث المعاملاتية.**','**API: gRPC بين الخدمات الداخلية.** أنظمة الصيرفة تعالج **آلاف المعاملات في الثانية**.','**الأمن: تشفير من طرف إلى طرف، HSM للمفاتيح.** المفاتيح التشفيرية تعيش في **HSM معتمد FIPS 140-2**.']},
      {heading:'التكلفة الحقيقية والجدول الزمني',body:['**نظام إدارة نقد كامل (5 وحدات):** 15-50 مليون دج. **المدة: 6-12 شهراً.**','**وحدة التقارير التنظيمية وحدها:** 3-8 مليون دج. **المدة: 2-4 أشهر.**','**مقارنة بـ Temenos:** المخصص يكلف **5-10 أضعاف أقل في الترخيص** والشيفرة لك من اليوم الأول.']},
      {heading:'لماذا نحن',body:['نحن **ورشة هندسة تبني أنظمة مصرفية من الصفر**. الشيفرة لك من اليوم الأول. لا ترخيص سنوي. لا قفل بائع.','نسلّم من **الجزائر العاصمة** بحضور محلي وفوترة بالدينار ومعرفة مباشرة بالمتطلبات التنظيمية المغاربية. نتحدث **الفرنسية والعربية والإنجليزية**.']},
    ],
    pullQuote1:'نظام إدارة النقد المصرفي ليس تطبيق ويب بقاعدة بيانات. إنه هندسة موزعة بمتطلبات لم يصادفها 90% من المطورين.',
    pullQuote2:'المخصص يكلف 5-10 أضعاف أقل في الترخيص من Temenos — والشيفرة لك من اليوم الأول.',
    cta:{eyebrow:'تحدث مع مهندس مصرفي',title:'تبني أو تحدّث نظاماً مصرفياً؟ صف مشروعك في 5 دقائق.'},
    related:{insights:[{key:'erp',name:'ERP مخصص — ما بعد أودو'},{key:'ai',name:'أتمتة الذكاء الاصطناعي'}],services:[{key:'software-engineering',name:'هندسة البرمجيات'},{key:'ai',name:'الذكاء الاصطناعي'}]},
  },
};

export default function Page(){const{locale}=useRouter();const isRtl=locale==='ar';const c=C[locale]||C.fr;const ld={'@context':'https://schema.org','@type':'BlogPosting',headline:c.title,description:c.dek,image:['https://symloop.com/blog/cover-logiciel-bancaire.jpg'],datePublished:'2026-04-15',author:{'@type':'Organization',name:'Symloop'},mainEntityOfPage:'https://symloop.com/blog/developpement-logiciel-bancaire-gestion-cash-2026/'};const bc=[{name:'Home',url:'https://symloop.com/'},{name:'Blog',url:'https://symloop.com/blog/'},{name:c.title,url:'https://symloop.com/blog/developpement-logiciel-bancaire-gestion-cash-2026/'}];
  return(<><SEO title={`Banking Software Development — Cash Management, Core Banking, SWIFT Integration | Symloop`} description={c.dek} keywords="banking software development, cash management system, core banking custom, développement logiciel bancaire, gestion cash banque maroc, banking software africa, SWIFT integration, core banking maghreb, fintech banking MENA, logiciel bancaire maroc tunisie algérie, cash management banking software, banking software development, SWIFT integration, système de paiement bancaire, fintech banking software, Temenos alternative, software bancaire maghreb, logiciel gestion trésorerie banque" type="article" structuredData={ld} breadcrumbs={bc} image="/blog/cover-logiciel-bancaire.jpg"/>
    <main dir={isRtl?'rtl':'ltr'} className="bg-black text-white">
      <section className="relative border-b border-white/[0.06]"><div className="max-w-5xl mx-auto px-6 lg:px-10 pt-32 lg:pt-40 pb-16"><motion.div initial="hidden" animate="show" variants={st}><motion.div variants={f} className="flex items-center gap-3 mb-8"><Link href="/blog/" className="font-mono text-[11px] tracking-[0.2em] uppercase text-white/40 hover:text-white transition-colors">{c.kind}</Link><span className="h-px w-12 bg-white/20"/><span className="font-mono text-[11px] tracking-[0.15em] uppercase text-white/35">{c.publishedAt}</span></motion.div><motion.h1 variants={f} className="text-4xl lg:text-6xl xl:text-7xl font-light tracking-tight leading-[1.05]">{c.title}</motion.h1><motion.p variants={f} className="mt-8 text-xl lg:text-2xl text-white/60 leading-relaxed font-light max-w-3xl">{c.dek}</motion.p><motion.div variants={f} className="mt-12 flex flex-wrap items-center gap-x-10 gap-y-3 font-mono text-[11px] tracking-[0.15em] uppercase text-white/35 pt-8 border-t border-white/[0.08]"><span>{c.author}</span><span>{c.readTime}</span></motion.div></motion.div></div><div className="relative w-full aspect-[16/9] lg:aspect-[21/9] border-y border-white/[0.06] bg-white/[0.02] overflow-hidden"><Image src="/blog/cover-logiciel-bancaire.jpg" alt={c.title} fill priority sizes="100vw" className="object-cover"/></div></section>
      <article className="max-w-3xl mx-auto px-6 lg:px-10 py-20 lg:py-28"><motion.div initial="hidden" whileInView="show" viewport={{once:true,margin:'-100px'}} variants={st} className="space-y-7 mb-20">{c.intro.map((p,i)=><motion.p key={i} variants={f} className="text-xl lg:text-2xl text-white/80 leading-[1.55] font-light">{R(p)}</motion.p>)}</motion.div>
        {c.sections.map((s,idx)=>(<div key={idx}><motion.section initial="hidden" whileInView="show" viewport={{once:true,margin:'-100px'}} variants={st} className="mb-12 lg:mb-16"><motion.div variants={f} className="flex items-baseline gap-5 mb-6"><span className="font-mono text-xs tracking-[0.15em] text-white/30">{String(idx+1).padStart(2,'0')}</span><h2 className="text-2xl lg:text-4xl font-light tracking-tight text-white leading-[1.1]">{s.heading}</h2></motion.div><div className="space-y-5 ps-0 lg:ps-10">{s.body.map((p,i)=><motion.p key={i} variants={f} className="text-lg lg:text-xl text-white/70 leading-[1.65]">{R(p)}</motion.p>)}</div></motion.section>{idx===2&&c.pullQuote1&&<motion.figure initial={{opacity:0,y:30}} whileInView={{opacity:1,y:0}} viewport={{once:true}} transition={{duration:0.7}} className="my-20 lg:my-24 border-y border-white/[0.08] py-12 lg:py-16"><blockquote className="text-3xl lg:text-4xl xl:text-5xl font-light tracking-tight text-white leading-[1.15]">«{c.pullQuote1}»</blockquote></motion.figure>}{idx===4&&c.pullQuote2&&<motion.figure initial={{opacity:0,y:30}} whileInView={{opacity:1,y:0}} viewport={{once:true}} transition={{duration:0.7}} className="my-20 lg:my-24 border-y border-white/[0.08] py-12 lg:py-16"><blockquote className="text-3xl lg:text-4xl xl:text-5xl font-light tracking-tight text-white leading-[1.15]">«{c.pullQuote2}»</blockquote></motion.figure>}</div>))}</article>
      <section className="border-t border-white/[0.06]"><div className="max-w-7xl mx-auto px-6 lg:px-10 py-24 lg:py-32"><div className="grid grid-cols-1 lg:grid-cols-12 gap-12"><div className="lg:col-span-6"><div className="flex items-center gap-3 mb-8"><span className="font-mono text-[11px] tracking-[0.2em] uppercase text-white/40">{c.cta.eyebrow}</span><span className="h-px w-12 bg-white/20"/></div><h2 className="text-3xl lg:text-5xl font-light tracking-tight leading-[1.1] mb-10">{c.cta.title}</h2><a href={W} target="_blank" rel="noopener noreferrer" className="group inline-flex items-center gap-3 bg-white text-black px-8 py-4 text-sm font-medium tracking-wide hover:bg-white/90 transition-colors"><MessageCircle className="w-4 h-4" strokeWidth={1.75}/><span>WhatsApp</span><ArrowRight className="w-4 h-4 transition-transform group-hover:translate-x-1" strokeWidth={1.75}/></a></div><div className="lg:col-span-6"><ul className="space-y-px bg-white/[0.06] border border-white/[0.06]">{c.related.insights.map(it=><li key={it.key} className="bg-black"><Link href={`/insights/${it.key}/`} className="group block p-6 transition-colors hover:bg-white/[0.025]"><div className="font-mono text-[10px] tracking-[0.2em] uppercase text-white/40 mb-2">Insight</div><h3 className="text-base font-light text-white leading-snug">{it.name}</h3></Link></li>)}{c.related.services.map(s=><li key={s.key} className="bg-black"><Link href={`/services/${s.key}/`} className="group block p-6 transition-colors hover:bg-white/[0.025]"><div className="font-mono text-[10px] tracking-[0.2em] uppercase text-white/40 mb-2">Service</div><h3 className="text-base font-light text-white leading-snug">{s.name}</h3></Link></li>)}</ul></div></div></div></section>
    </main></>);
}
export async function getStaticProps({locale}){return{props:{...(await serverSideTranslations(locale,['common']))}};}
