"use client";
import { useRouter } from 'next/router';
import Link from 'next/link';
import Head from 'next/head';
import { serverSideTranslations } from 'next-i18next/serverSideTranslations';
import { ArrowLeft, Calendar, Clock, User, MapPin, Code, Smartphone, Brain, CheckCircle, Phone, Mail, Building2, Rocket, Users, Shield, Zap, Star, Award, Globe, TrendingUp, Target, Database, CreditCard, ShoppingCart, BarChart3, Layers, MessageCircle, Briefcase, FileText, Settings, PieChart, Lock } from "lucide-react";

export default function DigitalTransformationKuwaitNewKuwait2030() {
  const router = useRouter();
  const locale = router.locale || 'en';
  const isRTL = locale === 'ar';
  const content = {
    en: {
      metaTitle: "Digital Transformation Kuwait 2026 | New Kuwait 2035 Strategy | Symloop",
      metaDescription: "Digital transformation solutions in Kuwait aligned with New Kuwait 2035 vision. Digital strategy, cloud migration, process automation, data analytics. Kuwait City, Hawalli, Salmiya.",
      title: "Digital Transformation in Kuwait - New Kuwait 2035",
      subtitle: "Accelerating Kuwait's Digital Economy Under the New Kuwait 2035 National Vision",
      category: "Digital Transformation", readTime: "18 min", author: "Symloop Team", date: "2026-01-15", backLink: "Back to Blog",
      intro: "Kuwait's New Kuwait 2035 vision is driving one of the most ambitious digital transformation programs in the Gulf region, with a $30 billion+ target for non-oil economic diversification. The government has committed to 100% e-government services, while over 60% of private sector companies are actively adopting digital technologies. With 70%+ of Kuwaiti businesses now digitalizing their operations, the country is rapidly evolving into a smart, connected economy. Symloop partners with organizations across Kuwait to design and implement comprehensive digital transformation strategies that align with New Kuwait 2035 goals, delivering measurable results through cloud migration, process automation, data analytics, and modern digital infrastructure.",
      statsTitle: "Kuwait Digital Economy 2026",
      stats: [{ value: "$30B+", label: "Non-Oil Target" }, { value: "100%", label: "E-Government" }, { value: "60%+", label: "Digital Adoption" }, { value: "70%+", label: "Digitalizing" }],
      services: { title: "Our Digital Transformation Services", subtitle: "End-to-end digital transformation for Kuwait's New Kuwait 2035 vision", list: [
        { icon: Target, title: "Digital Strategy & Consulting", description: "Comprehensive digital transformation roadmaps aligned with New Kuwait 2035 objectives for Kuwaiti businesses and government entities.", features: ["Digital maturity assessment", "Technology roadmap development", "Change management planning", "ROI modeling and KPI definition"] },
        { icon: Database, title: "Cloud Migration & Infrastructure", description: "Secure cloud migration services to modernize IT infrastructure for Kuwaiti organizations. AWS, Azure, and Google Cloud certified.", features: ["Cloud readiness assessment", "Hybrid and multi-cloud architecture", "Data migration and validation", "Cloud security and compliance"] },
        { icon: Zap, title: "Process Automation & BPM", description: "Business process automation to eliminate manual tasks, reduce errors, and accelerate operations across Kuwaiti organizations.", features: ["Workflow automation (RPA)", "Business process modeling", "Document digitization", "Integration with legacy systems"] },
        { icon: BarChart3, title: "Data Analytics & Business Intelligence", description: "Transform raw data into actionable insights with advanced analytics platforms designed for the Kuwaiti market.", features: ["Data warehouse design", "Real-time dashboards", "Predictive analytics", "Self-service BI tools"] }
      ] },
      digitalVision: { title: "Aligned with New Kuwait 2035 Vision", description: "New Kuwait 2035 is Kuwait's ambitious national development plan that aims to transform the country into a financial and trade hub led by the private sector. The vision emphasizes digital transformation across all sectors including government, healthcare, education, finance, and infrastructure. Our digital transformation services are specifically designed to help Kuwaiti organizations contribute to and benefit from this national vision, ensuring technology investments deliver maximum impact for both business growth and national development goals.",
        features: ["E-government digital services platform development", "Smart city infrastructure for Kuwait municipalities", "Digital banking and fintech innovation (KNET integration)", "Healthcare information systems and telemedicine", "Education technology and e-learning platforms", "Oil & gas digital twin and IoT solutions", "Retail and e-commerce digital ecosystems", "Supply chain digitization and logistics optimization"] },
      cities: { title: "Digital Transformation Across Kuwait", list: [{ name: "Kuwait City", desc: "Digital hub capital" }, { name: "Hawalli", desc: "Business transformation" }, { name: "Salmiya", desc: "Retail digitalization" }, { name: "Farwaniya", desc: "Industrial digital" }, { name: "Jahra", desc: "Emerging digital zone" }] },
      sectors: { title: "Digital Transformation by Sector", subtitle: "Industry-specific digital solutions for Kuwait", list: [{ name: "Oil & Gas", icon: Layers, desc: "Digital twins, IoT sensors, predictive analytics" }, { name: "Banking & Finance", icon: CreditCard, desc: "Digital banking, KNET innovation, open banking APIs" }, { name: "Government", icon: Globe, desc: "E-government, citizen portals, digital ID systems" }, { name: "Construction", icon: Building2, desc: "BIM, project management, smart construction" }, { name: "Real Estate", icon: Building2, desc: "PropTech, virtual tours, smart building management" }, { name: "Healthcare", icon: Shield, desc: "EMR systems, telemedicine, health analytics" }, { name: "Retail & E-commerce", icon: ShoppingCart, desc: "Omnichannel retail, KNET payments, digital marketing" }, { name: "Education", icon: Award, desc: "LMS platforms, virtual classrooms, EdTech solutions" }, { name: "Telecommunications", icon: Smartphone, desc: "5G services, network digitization, customer platforms" }] },
      whyUs: { title: "Why Choose Symloop for Digital Transformation", reasons: [{ title: "New Kuwait 2035 Expertise", desc: "Deep understanding of Kuwait's national vision and digital transformation priorities.", icon: Globe }, { title: "Kuwait Market Knowledge", desc: "Solutions designed for Kuwait's unique regulatory and business environment.", icon: Target }, { title: "Proven Methodology", desc: "Structured approach to digital transformation with measurable milestones and KPIs.", icon: Brain }, { title: "Rapid Implementation", desc: "Quick wins within 4-8 weeks while building toward long-term digital maturity.", icon: Zap }, { title: "Technology Agnostic", desc: "Best-of-breed technology selection based on your specific needs, not vendor lock-in.", icon: TrendingUp }, { title: "Data Security", desc: "Enterprise-grade security compliant with Kuwait's data protection regulations.", icon: Lock }, { title: "Change Management", desc: "People-first approach ensuring adoption and cultural transformation alongside technology.", icon: Users }, { title: "Ongoing Partnership", desc: "Long-term digital transformation partner, not just a technology vendor.", icon: MessageCircle }] },
      pricing: { title: "Digital Transformation Pricing in Kuwait", subtitle: "Transparent pricing in KWD.", plans: [
        { name: "Digital Assessment", price: "From 3,000 KWD", features: ["Digital maturity assessment", "Technology audit", "Transformation roadmap", "Quick-win identification", "Executive summary"], color: "gray", popular: false },
        { name: "Digital Professional", price: "From 12,000 KWD", features: ["Full strategy development", "Cloud migration plan", "Process automation", "6 months support", "Dashboard & analytics", "Training included"], color: "cyan", popular: true },
        { name: "Digital Enterprise", price: "From 30,000 KWD", features: ["Enterprise transformation", "Multi-department scope", "Advanced analytics", "12 months support", "Change management", "Priority support"], color: "gray", popular: false },
        { name: "Custom Program", price: "On Quote", features: ["Full organizational transformation", "Multi-year roadmap", "Dedicated team", "Executive coaching", "SLA agreement", "On-site presence"], color: "gray", popular: false }
      ] },
      faq: { title: "Frequently Asked Questions", items: [
        { q: "How does digital transformation align with New Kuwait 2035?", a: "New Kuwait 2035 prioritizes economic diversification through technology and innovation. Our digital transformation services directly support this by modernizing business operations, enabling e-commerce and digital services, automating government processes, and building the digital infrastructure needed for a knowledge-based economy." },
        { q: "How long does a digital transformation project take?", a: "A digital maturity assessment takes 2-4 weeks. Strategy development is 4-8 weeks. Implementation phases typically run 3-12 months depending on scope. We use an agile approach with quick wins every 4-6 weeks to demonstrate value early." },
        { q: "What is the ROI of digital transformation?", a: "Organizations typically see 20-40% cost reduction through process automation, 30-50% faster time-to-market, 25-35% improvement in customer satisfaction, and 15-25% revenue growth through new digital channels. We establish clear KPIs and measure ROI throughout the transformation." },
        { q: "Do you support Arabic-language digital systems?", a: "Yes, all our digital solutions support Arabic and English interfaces with full RTL support. We ensure all digital platforms, e-commerce systems, and customer-facing applications provide excellent Arabic-language experiences for Kuwaiti users." },
        { q: "Can you transform our legacy systems without disrupting operations?", a: "Absolutely. We use a phased approach to digital transformation that minimizes disruption. Legacy systems are integrated using APIs and middleware before gradual migration. We ensure business continuity throughout the transformation process." }
      ] },
      cta: { title: "Ready to Transform Your Business Digitally?", subtitle: "Get a free digital maturity assessment and transformation roadmap", whatsapp: "Contact on WhatsApp", email: "Send Email", phone: "+213549575512", emailAddr: "contact@symloop.com" },
      related: { title: "Related Articles", posts: [{ title: "Web Development Company Kuwait 2026", slug: "web-development-company-kuwait-2026" }, { title: "ERP & Business Software Kuwait 2026", slug: "erp-business-software-kuwait-2026" }, { title: "AI Solutions Kuwait 2026", slug: "artificial-intelligence-solutions-kuwait-2026" }] },
      seoKeywords: "digital transformation Kuwait, New Kuwait 2035, digital strategy Kuwait, cloud migration Kuwait, process automation Kuwait, data analytics Kuwait, e-government Kuwait, smart city Kuwait, digital economy Kuwait, business transformation Kuwait City, digital Kuwait 2026, IT modernization Kuwait KWD"
    },
    ar: {
      metaTitle: "التحول الرقمي في الكويت 2026 | استراتيجية كويت جديدة 2035 | سيملوب",
      metaDescription: "حلول التحول الرقمي في الكويت متوافقة مع رؤية كويت جديدة 2035. استراتيجية رقمية، هجرة سحابية، أتمتة العمليات. مدينة الكويت، حولي، السالمية.",
      title: "التحول الرقمي في الكويت - كويت جديدة 2035",
      subtitle: "تسريع الاقتصاد الرقمي الكويتي ضمن رؤية كويت جديدة 2035 الوطنية",
      category: "التحول الرقمي", readTime: "18 دقيقة", author: "فريق سيملوب", date: "2026-01-15", backLink: "العودة للمدونة",
      intro: "تدفع رؤية كويت جديدة 2035 أحد أكثر برامج التحول الرقمي طموحاً في منطقة الخليج، مع هدف يتجاوز 30 مليار دولار للتنويع الاقتصادي غير النفطي. التزمت الحكومة بتقديم 100% من خدمات الحكومة الإلكترونية، بينما أكثر من 60% من شركات القطاع الخاص تتبنى التقنيات الرقمية بنشاط. مع أكثر من 70% من الشركات الكويتية التي ترقمن عملياتها الآن، يتطور البلد بسرعة نحو اقتصاد ذكي ومتصل. سيملوب تتشارك مع المؤسسات في الكويت لتصميم وتنفيذ استراتيجيات تحول رقمي شاملة.",
      statsTitle: "الاقتصاد الرقمي الكويتي 2026",
      stats: [{ value: "+30 مليار$", label: "هدف غير نفطي" }, { value: "100%", label: "حكومة إلكترونية" }, { value: "+60%", label: "تبني رقمي" }, { value: "+70%", label: "في طور الرقمنة" }],
      services: { title: "خدمات التحول الرقمي لدينا", subtitle: "تحول رقمي شامل لرؤية كويت جديدة 2035", list: [
        { icon: Target, title: "الاستراتيجية الرقمية والاستشارات", description: "خرائط طريق تحول رقمي شاملة متوافقة مع أهداف كويت جديدة 2035.", features: ["تقييم النضج الرقمي", "تطوير خارطة طريق تقنية", "تخطيط إدارة التغيير", "نمذجة ROI وتحديد KPI"] },
        { icon: Database, title: "الهجرة السحابية والبنية التحتية", description: "خدمات هجرة سحابية آمنة لتحديث البنية التحتية لتكنولوجيا المعلومات.", features: ["تقييم جاهزية السحابة", "بنية سحابية هجينة ومتعددة", "نقل البيانات والتحقق منها", "أمان وامتثال سحابي"] },
        { icon: Zap, title: "أتمتة العمليات وإدارة الأعمال", description: "أتمتة العمليات التجارية للقضاء على المهام اليدوية وتقليل الأخطاء.", features: ["أتمتة سير العمل (RPA)", "نمذجة العمليات التجارية", "رقمنة المستندات", "التكامل مع الأنظمة القديمة"] },
        { icon: BarChart3, title: "تحليلات البيانات وذكاء الأعمال", description: "تحويل البيانات الخام إلى رؤى قابلة للتنفيذ مع منصات تحليلات متقدمة.", features: ["تصميم مستودع البيانات", "لوحات معلومات في الوقت الفعلي", "تحليلات تنبؤية", "أدوات BI للخدمة الذاتية"] }
      ] },
      digitalVision: { title: "متوافق مع رؤية كويت جديدة 2035", description: "كويت جديدة 2035 هي خطة التنمية الوطنية الطموحة التي تهدف إلى تحويل البلاد إلى مركز مالي وتجاري يقوده القطاع الخاص. تؤكد الرؤية على التحول الرقمي في جميع القطاعات. خدمات التحول الرقمي لدينا مصممة خصيصاً لمساعدة المؤسسات الكويتية على المساهمة في هذه الرؤية الوطنية والاستفادة منها.",
        features: ["تطوير منصات الخدمات الحكومية الرقمية", "بنية تحتية للمدن الذكية لبلديات الكويت", "ابتكار الخدمات المصرفية الرقمية والتكنولوجيا المالية (تكامل KNET)", "أنظمة معلومات صحية والطب عن بُعد", "تكنولوجيا التعليم ومنصات التعلم الإلكتروني", "التوأم الرقمي وإنترنت الأشياء للنفط والغاز", "أنظمة بيئة التجزئة والتجارة الإلكترونية الرقمية", "رقمنة سلسلة التوريد وتحسين اللوجستيات"] },
      cities: { title: "التحول الرقمي في أنحاء الكويت", list: [{ name: "مدينة الكويت", desc: "عاصمة المركز الرقمي" }, { name: "حولي", desc: "تحول الأعمال" }, { name: "السالمية", desc: "رقمنة التجزئة" }, { name: "الفروانية", desc: "رقمنة صناعية" }, { name: "الجهراء", desc: "منطقة رقمية ناشئة" }] },
      sectors: { title: "التحول الرقمي حسب القطاع", subtitle: "حلول رقمية متخصصة لقطاعات الكويت", list: [{ name: "النفط والغاز", icon: Layers, desc: "التوائم الرقمية، مستشعرات IoT، تحليلات تنبؤية" }, { name: "البنوك والتمويل", icon: CreditCard, desc: "خدمات مصرفية رقمية، ابتكار KNET، APIs مفتوحة" }, { name: "القطاع الحكومي", icon: Globe, desc: "حكومة إلكترونية، بوابات المواطنين، أنظمة هوية رقمية" }, { name: "البناء والتشييد", icon: Building2, desc: "BIM، إدارة مشاريع، بناء ذكي" }, { name: "العقارات", icon: Building2, desc: "PropTech، جولات افتراضية، إدارة مبانٍ ذكية" }, { name: "الرعاية الصحية", icon: Shield, desc: "أنظمة EMR، طب عن بُعد، تحليلات صحية" }, { name: "التجزئة والتجارة الإلكترونية", icon: ShoppingCart, desc: "تجزئة متعددة القنوات، مدفوعات KNET، تسويق رقمي" }, { name: "التعليم", icon: Award, desc: "منصات LMS، فصول افتراضية، حلول EdTech" }, { name: "الاتصالات", icon: Smartphone, desc: "خدمات 5G، رقمنة الشبكات، منصات العملاء" }] },
      whyUs: { title: "لماذا تختار سيملوب للتحول الرقمي", reasons: [{ title: "خبرة كويت جديدة 2035", desc: "فهم عميق لرؤية الكويت الوطنية وأولويات التحول الرقمي.", icon: Globe }, { title: "معرفة السوق الكويتي", desc: "حلول مصممة لبيئة الأعمال والتنظيم الكويتية الفريدة.", icon: Target }, { title: "منهجية مثبتة", desc: "نهج منظم للتحول الرقمي مع معالم قابلة للقياس.", icon: Brain }, { title: "تنفيذ سريع", desc: "مكاسب سريعة خلال 4-8 أسابيع مع البناء نحو النضج الرقمي.", icon: Zap }, { title: "محايد تقنياً", desc: "اختيار أفضل التقنيات بناءً على احتياجاتك المحددة.", icon: TrendingUp }, { title: "أمان البيانات", desc: "أمان على مستوى المؤسسات متوافق مع لوائح حماية البيانات الكويتية.", icon: Lock }, { title: "إدارة التغيير", desc: "نهج يضع الأشخاص أولاً لضمان التبني والتحول الثقافي.", icon: Users }, { title: "شراكة مستمرة", desc: "شريك تحول رقمي طويل الأمد وليس مجرد مزود تقنية.", icon: MessageCircle }] },
      pricing: { title: "أسعار التحول الرقمي في الكويت", subtitle: "أسعار شفافة بالدينار الكويتي.", plans: [
        { name: "تقييم رقمي", price: "من 3,000 د.ك", features: ["تقييم النضج الرقمي", "تدقيق تقني", "خارطة طريق التحول", "تحديد المكاسب السريعة", "ملخص تنفيذي"], color: "gray", popular: false },
        { name: "تحول احترافي", price: "من 12,000 د.ك", features: ["تطوير استراتيجية كاملة", "خطة هجرة سحابية", "أتمتة العمليات", "6 أشهر دعم", "لوحة تحكم وتحليلات", "تدريب مشمول"], color: "cyan", popular: true },
        { name: "تحول مؤسسي", price: "من 30,000 د.ك", features: ["تحول مؤسسي شامل", "نطاق متعدد الأقسام", "تحليلات متقدمة", "12 شهر دعم", "إدارة التغيير", "دعم أولوية"], color: "gray", popular: false },
        { name: "برنامج مخصص", price: "حسب الطلب", features: ["تحول مؤسسي كامل", "خارطة طريق متعددة السنوات", "فريق مخصص", "تدريب تنفيذي", "اتفاقية SLA", "تواجد في الموقع"], color: "gray", popular: false }
      ] },
      faq: { title: "الأسئلة الشائعة", items: [
        { q: "كيف يتوافق التحول الرقمي مع رؤية كويت جديدة 2035؟", a: "تعطي كويت جديدة 2035 الأولوية للتنويع الاقتصادي من خلال التكنولوجيا والابتكار. خدمات التحول الرقمي لدينا تدعم ذلك مباشرة من خلال تحديث العمليات التجارية وتمكين التجارة الإلكترونية والخدمات الرقمية." },
        { q: "كم يستغرق مشروع التحول الرقمي؟", a: "تقييم النضج الرقمي يستغرق 2-4 أسابيع. تطوير الاستراتيجية 4-8 أسابيع. مراحل التنفيذ 3-12 شهراً حسب النطاق. نستخدم نهجاً رشيقاً مع مكاسب سريعة كل 4-6 أسابيع." },
        { q: "ما العائد على الاستثمار من التحول الرقمي؟", a: "المؤسسات تحقق عادةً تخفيض 20-40% في التكاليف، تسريع 30-50% في الوصول للسوق، تحسين 25-35% في رضا العملاء، ونمو 15-25% في الإيرادات." },
        { q: "هل تدعمون الأنظمة الرقمية باللغة العربية؟", a: "نعم، جميع حلولنا الرقمية تدعم واجهات عربية وإنجليزية مع دعم كامل لـ RTL. نضمن تجربة ممتازة باللغة العربية." },
        { q: "هل يمكنكم تحويل أنظمتنا القديمة دون تعطيل العمليات؟", a: "بالتأكيد. نستخدم نهجاً تدريجياً يقلل التعطيل. يتم دمج الأنظمة القديمة باستخدام APIs ووسيط قبل الترحيل التدريجي." }
      ] },
      cta: { title: "هل أنت مستعد لتحويل أعمالك رقمياً؟", subtitle: "احصل على تقييم مجاني للنضج الرقمي وخارطة طريق للتحول", whatsapp: "تواصل عبر واتساب", email: "أرسل بريداً إلكترونياً", phone: "+213549575512", emailAddr: "contact@symloop.com" },
      related: { title: "مقالات ذات صلة", posts: [{ title: "تطوير مواقع الويب الكويت", slug: "web-development-company-kuwait-2026" }, { title: "حلول ERP الكويت", slug: "erp-business-software-kuwait-2026" }, { title: "حلول AI الكويت", slug: "artificial-intelligence-solutions-kuwait-2026" }] },
      seoKeywords: "التحول الرقمي الكويت, كويت جديدة 2035, استراتيجية رقمية الكويت, هجرة سحابية الكويت, أتمتة العمليات الكويت, تحليلات البيانات الكويت, حكومة إلكترونية الكويت, مدينة ذكية الكويت"
    },
    fr: {
      metaTitle: "Transformation Digitale Koweït 2026 | Nouveau Koweït 2035 | Symloop",
      metaDescription: "Solutions de transformation digitale au Koweït alignées sur Nouveau Koweït 2035. Stratégie digitale, migration cloud, automatisation. Koweït City, Hawalli, Salmiya.",
      title: "Transformation Digitale au Koweït - Nouveau Koweït 2035",
      subtitle: "Accélérer l'économie numérique du Koweït sous la vision nationale Nouveau Koweït 2035",
      category: "Transformation Digitale", readTime: "18 min", author: "Equipe Symloop", date: "2026-01-15", backLink: "Retour au Blog",
      intro: "La vision Nouveau Koweït 2035 pilote l'un des programmes de transformation digitale les plus ambitieux de la région du Golfe, avec un objectif de 30 milliards de dollars+ pour la diversification économique non pétrolière. Le gouvernement s'est engagé à 100% de services e-gouvernement, tandis que plus de 60% des entreprises du secteur privé adoptent activement les technologies numériques. Avec 70%+ des entreprises koweïtiennes en cours de digitalisation, le pays évolue rapidement vers une économie connectée et intelligente.",
      statsTitle: "Économie Digitale Koweït 2026",
      stats: [{ value: "30Mds$+", label: "Objectif Non-Pétrole" }, { value: "100%", label: "E-Gouvernement" }, { value: "60%+", label: "Adoption Digitale" }, { value: "70%+", label: "En Digitalisation" }],
      services: { title: "Nos Services de Transformation", subtitle: "Transformation digitale complète pour Nouveau Koweït 2035", list: [
        { icon: Target, title: "Stratégie Digitale & Conseil", description: "Feuilles de route de transformation alignées sur Nouveau Koweït 2035.", features: ["Évaluation maturité digitale", "Roadmap technologique", "Plan gestion du changement", "Modélisation ROI et KPI"] },
        { icon: Database, title: "Migration Cloud & Infrastructure", description: "Migration cloud sécurisée pour moderniser l'infrastructure IT koweïtienne.", features: ["Évaluation cloud readiness", "Architecture hybride/multi-cloud", "Migration et validation données", "Sécurité cloud et conformité"] },
        { icon: Zap, title: "Automatisation & BPM", description: "Automatisation des processus pour éliminer les tâches manuelles.", features: ["Automatisation workflows (RPA)", "Modélisation processus", "Numérisation documents", "Intégration systèmes legacy"] },
        { icon: BarChart3, title: "Analytics & Business Intelligence", description: "Transformer les données en insights actionnables.", features: ["Data warehouse", "Dashboards temps réel", "Analytics prédictives", "Outils BI self-service"] }
      ] },
      digitalVision: { title: "Aligné sur Nouveau Koweït 2035", description: "Nouveau Koweït 2035 vise à transformer le pays en hub financier et commercial. Nos services de transformation digitale sont conçus pour aider les organisations koweïtiennes à contribuer à cette vision nationale.",
        features: ["Plateformes services gouvernementaux digitaux", "Infrastructure ville intelligente", "Innovation bancaire digitale (KNET)", "Systèmes santé et télémédecine", "EdTech et e-learning", "Jumeaux numériques pétrole & gaz", "Écosystèmes retail et e-commerce", "Digitalisation supply chain"] },
      cities: { title: "Transformation au Koweït", list: [{ name: "Koweït City", desc: "Hub digital capital" }, { name: "Hawalli", desc: "Transformation business" }, { name: "Salmiya", desc: "Digitalisation retail" }, { name: "Farwaniya", desc: "Digital industriel" }, { name: "Jahra", desc: "Zone digitale émergente" }] },
      sectors: { title: "Transformation par Secteur", subtitle: "Solutions digitales sectorielles pour le Koweït", list: [{ name: "Pétrole & Gaz", icon: Layers, desc: "Jumeaux numériques, IoT, analytics" }, { name: "Banque & Finance", icon: CreditCard, desc: "Banque digitale, KNET, APIs ouvertes" }, { name: "Gouvernement", icon: Globe, desc: "E-gouvernement, portails citoyens" }, { name: "Construction", icon: Building2, desc: "BIM, gestion projet, construction smart" }, { name: "Immobilier", icon: Building2, desc: "PropTech, visites virtuelles, smart building" }, { name: "Santé", icon: Shield, desc: "EMR, télémédecine, analytics santé" }, { name: "Retail & E-commerce", icon: ShoppingCart, desc: "Omnicanal, paiements KNET" }, { name: "Éducation", icon: Award, desc: "LMS, classes virtuelles, EdTech" }, { name: "Télécoms", icon: Smartphone, desc: "5G, digitalisation réseau" }] },
      whyUs: { title: "Pourquoi Symloop pour la Transformation", reasons: [{ title: "Expertise 2035", desc: "Connaissance approfondie de la vision nationale koweïtienne.", icon: Globe }, { title: "Marché Koweïtien", desc: "Solutions adaptées à l'environnement réglementaire koweïtien.", icon: Target }, { title: "Méthodologie Prouvée", desc: "Approche structurée avec jalons mesurables.", icon: Brain }, { title: "Mise en Oeuvre Rapide", desc: "Quick wins en 4-8 semaines.", icon: Zap }, { title: "Agnostique Tech", desc: "Sélection best-of-breed sans vendor lock-in.", icon: TrendingUp }, { title: "Sécurité Données", desc: "Conforme réglementations koweïtiennes.", icon: Lock }, { title: "Gestion Changement", desc: "Approche people-first pour l'adoption.", icon: Users }, { title: "Partenariat Durable", desc: "Partenaire long terme, pas simple fournisseur.", icon: MessageCircle }] },
      pricing: { title: "Tarifs Transformation Koweït", subtitle: "Prix transparents en KWD.", plans: [
        { name: "Évaluation", price: "3 000 KWD", features: ["Maturité digitale", "Audit tech", "Roadmap", "Quick wins", "Résumé exécutif"], color: "gray", popular: false },
        { name: "Pro", price: "12 000 KWD", features: ["Stratégie complète", "Plan cloud", "Automatisation", "6 mois support", "Dashboard", "Formation"], color: "cyan", popular: true },
        { name: "Enterprise", price: "30 000 KWD", features: ["Transformation enterprise", "Multi-départements", "Analytics avancées", "12 mois", "Change management", "Priorité"], color: "gray", popular: false },
        { name: "Sur Mesure", price: "Sur Devis", features: ["Transformation totale", "Multi-années", "Équipe dédiée", "Coaching exécutif", "SLA", "Présence site"], color: "gray", popular: false }
      ] },
      faq: { title: "Questions Fréquentes", items: [
        { q: "Comment la transformation s'aligne sur Nouveau Koweït 2035 ?", a: "Nouveau Koweït 2035 priorise la diversification par la technologie. Nos services modernisent les opérations et construisent l'infrastructure digitale." },
        { q: "Durée d'un projet de transformation ?", a: "Évaluation: 2-4 semaines. Stratégie: 4-8 semaines. Implémentation: 3-12 mois. Approche agile avec quick wins toutes les 4-6 semaines." },
        { q: "Quel ROI espérer ?", a: "Typiquement: -20-40% coûts, +30-50% time-to-market, +25-35% satisfaction client, +15-25% revenus via canaux digitaux." },
        { q: "Support arabe disponible ?", a: "Oui, toutes nos solutions supportent arabe et anglais avec RTL complet." },
        { q: "Transformation sans disruption ?", a: "Oui, approche phasée avec intégration API des systèmes legacy avant migration progressive." }
      ] },
      cta: { title: "Prêt pour la transformation digitale ?", subtitle: "Évaluation gratuite de maturité digitale", whatsapp: "Contacter sur WhatsApp", email: "Envoyer un Email", phone: "+213549575512", emailAddr: "contact@symloop.com" },
      related: { title: "Articles Connexes", posts: [{ title: "Développement Web Koweït", slug: "web-development-company-kuwait-2026" }, { title: "ERP Koweït", slug: "erp-business-software-kuwait-2026" }, { title: "IA Koweït", slug: "artificial-intelligence-solutions-kuwait-2026" }] },
      seoKeywords: "transformation digitale Koweït, Nouveau Koweït 2035, stratégie digitale Koweït, migration cloud Koweït, automatisation Koweït, e-gouvernement Koweït, ville intelligente Koweït, transformation 2026"
    }
  };
  const c = content[locale] || content.en;
  const jsonLdArticle = { "@context": "https://schema.org", "@type": "Article", "headline": c.title, "description": c.metaDescription, "author": { "@type": "Organization", "name": "Symloop" }, "publisher": { "@type": "Organization", "name": "Symloop", "logo": { "@type": "ImageObject", "url": "https://symloop.com/logo.png" } }, "datePublished": "2026-01-15", "dateModified": "2026-01-15", "mainEntityOfPage": { "@type": "WebPage", "@id": "https://symloop.com/blog/digital-transformation-kuwait-new-kuwait-2030" }, "image": "https://symloop.com/logo.png", "inLanguage": locale, "keywords": c.seoKeywords };
  const jsonLdFaq = { "@context": "https://schema.org", "@type": "FAQPage", "mainEntity": c.faq.items.map(item => ({ "@type": "Question", "name": item.q, "acceptedAnswer": { "@type": "Answer", "text": item.a } })) };
  const jsonLdLocalBusiness = { "@context": "https://schema.org", "@type": "LocalBusiness", "name": "Symloop", "description": "Digital Transformation Consultancy in Kuwait", "url": "https://symloop.com", "telephone": "+213549575512", "email": "contact@symloop.com", "areaServed": { "@type": "Country", "name": "Kuwait" }, "serviceArea": [{ "@type": "City", "name": "Kuwait City" }, { "@type": "City", "name": "Hawalli" }, { "@type": "City", "name": "Salmiya" }, { "@type": "City", "name": "Farwaniya" }, { "@type": "City", "name": "Jahra" }], "priceRange": "$$" };

  return (<><Head><title>{c.metaTitle}</title><meta name="description" content={c.metaDescription} /><meta name="keywords" content={c.seoKeywords} /><link rel="canonical" href="https://symloop.com/blog/digital-transformation-kuwait-new-kuwait-2030" /><meta property="og:title" content={c.title} /><meta property="og:description" content={c.metaDescription} /><meta property="og:type" content="article" /><meta property="og:url" content="https://symloop.com/blog/digital-transformation-kuwait-new-kuwait-2030" /><meta property="og:site_name" content="Symloop" /><meta property="og:image" content="https://symloop.com/logo.png" /><meta property="og:locale" content={locale === 'ar' ? 'ar_KW' : locale === 'en' ? 'en_US' : 'fr_FR'} /><meta property="article:published_time" content={c.date || "2026-01-15"} /><meta property="article:modified_time" content="2026-02-07" /><meta property="article:section" content={c.category} /><meta name="twitter:card" content="summary_large_image" /><meta name="twitter:title" content={c.title} /><meta name="twitter:description" content={c.metaDescription} /><meta name="robots" content="index, follow" /><meta name="author" content="Symloop" /><meta name="geo.region" content="KW" /><meta name="geo.placename" content="Kuwait" /><link rel="alternate" hrefLang="en" href="https://symloop.com/en/blog/digital-transformation-kuwait-new-kuwait-2030" /><link rel="alternate" hrefLang="ar" href="https://symloop.com/ar/blog/digital-transformation-kuwait-new-kuwait-2030" /><link rel="alternate" hrefLang="fr" href="https://symloop.com/fr/blog/digital-transformation-kuwait-new-kuwait-2030" /><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLdArticle) }} /><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLdFaq) }} /><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLdLocalBusiness) }} /><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify({ "@context": "https://schema.org", "@type": "BreadcrumbList", "itemListElement": [{ "@type": "ListItem", "position": 1, "name": "Home", "item": "https://symloop.com" }, { "@type": "ListItem", "position": 2, "name": "Blog", "item": "https://symloop.com/blog" }, { "@type": "ListItem", "position": 3, "name": c.title }] }) }} /></Head>
    <article className={`min-h-screen bg-black text-white ${isRTL ? 'rtl' : 'ltr'}`} dir={isRTL ? 'rtl' : 'ltr'}>
      <section className="relative py-16 lg:py-24 overflow-hidden"><div className="absolute inset-0 bg-gradient-to-b from-cyan-500/10 via-black to-teal-500/10" /><div className="relative max-w-5xl mx-auto px-4 sm:px-6 lg:px-8"><Link href="/blog" className="inline-flex items-center gap-2 text-gray-400 hover:text-cyan-400 mb-8 transition-colors"><ArrowLeft className={`w-4 h-4 ${isRTL ? 'rotate-180' : ''}`} />{c.backLink}</Link><div className="flex flex-wrap items-center gap-3 mb-6"><span className="bg-cyan-500 text-white px-4 py-1.5 rounded-full text-sm font-medium flex items-center gap-2"><Rocket className="w-4 h-4" />{c.category}</span><span className="text-gray-400 text-sm flex items-center gap-1"><Clock className="w-3.5 h-3.5" />{c.readTime}</span></div><h1 className="text-3xl sm:text-4xl lg:text-5xl xl:text-6xl font-bold mb-6 leading-tight"><span className="text-cyan-400">{locale === 'ar' ? 'التحول الرقمي' : locale === 'fr' ? 'Transformation Digitale' : 'Digital Transformation'}</span>{locale === 'ar' ? ' في الكويت' : locale === 'fr' ? ' au Koweït' : ' in Kuwait'}</h1><p className="text-lg lg:text-xl text-gray-300 mb-8 max-w-3xl">{c.subtitle}</p><div className="flex flex-wrap items-center gap-6 text-gray-400 text-sm"><div className="flex items-center gap-2"><User className="w-4 h-4" />{c.author}</div><div className="flex items-center gap-2"><Calendar className="w-4 h-4" />{c.date}</div><div className="flex items-center gap-2"><MapPin className="w-4 h-4" />{locale === 'ar' ? 'الكويت' : 'Kuwait'}</div></div></div></section>
      <section className="py-12"><div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8"><p className="text-lg text-gray-300 leading-relaxed">{c.intro}</p>
            <p className="text-base text-gray-400 mt-6 leading-relaxed">
              {locale === 'ar'
                ? <>استكشف أيضاً <Link href="/services" className="text-cyan-400 hover:underline">خدماتنا الكاملة</Link> بما في ذلك <Link href="/blog/artificial-intelligence-solutions-kuwait-2026" className="text-cyan-400 hover:underline">حلول الذكاء الاصطناعي في الكويت</Link> و<Link href="/blog/digital-transformation-uae-smart-government-2026" className="text-cyan-400 hover:underline">التحول الرقمي في الإمارات</Link>.</>
                : <>Explore our full range of <Link href="/services" className="text-cyan-400 hover:underline">IT services</Link>, including <Link href="/blog/artificial-intelligence-solutions-kuwait-2026" className="text-cyan-400 hover:underline">AI solutions in Kuwait</Link> and <Link href="/blog/digital-transformation-uae-smart-government-2026" className="text-cyan-400 hover:underline">digital transformation in the UAE</Link>.</>
              }
            </p></div></section>
      <section className="py-12"><div className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8"><div className="bg-gradient-to-r from-cyan-900/40 to-teal-800/20 border border-cyan-500/30 rounded-2xl p-8"><h2 className="text-2xl font-bold text-white mb-8 text-center flex items-center justify-center gap-3"><TrendingUp className="w-6 h-6 text-cyan-400" />{c.statsTitle}</h2><div className="grid grid-cols-2 md:grid-cols-4 gap-6">{c.stats.map((s, i) => (<div key={i} className="text-center"><div className="text-3xl lg:text-4xl font-bold text-cyan-400">{s.value}</div><div className="text-sm text-gray-400 mt-2">{s.label}</div></div>))}</div></div></div></section>
      <section className="py-16"><div className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8"><div className="text-center mb-12"><h2 className="text-3xl lg:text-4xl font-bold text-white mb-4">{c.services.title}</h2><p className="text-gray-400 text-lg">{c.services.subtitle}</p></div><div className="grid md:grid-cols-2 gap-6">{c.services.list.map((s, i) => { const I = s.icon; return (<div key={i} className="bg-gray-900/60 border border-gray-800 rounded-2xl p-6 hover:border-cyan-500/50 transition-all duration-300"><div className="w-12 h-12 bg-cyan-500/20 rounded-xl flex items-center justify-center mb-4"><I className="w-6 h-6 text-cyan-400" /></div><h3 className="text-xl font-bold text-white mb-3">{s.title}</h3><p className="text-gray-400 mb-4">{s.description}</p><ul className="space-y-2">{s.features.map((f, j) => (<li key={j} className="flex items-center gap-2 text-gray-300 text-sm"><CheckCircle className="w-4 h-4 text-cyan-500 flex-shrink-0" />{f}</li>))}</ul></div>); })}</div></div></section>

        {/* ==================== MID-CONTENT CTA ==================== */}
        <section className="py-8">
          <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
            <div className="bg-gradient-to-r from-cyan-900/30 to-teal-900/20 border border-cyan-500/20 rounded-xl p-6 text-center">
              <p className="text-white text-lg mb-3">
                {locale === 'ar' ? 'هل تحتاج استشارة مجانية لمشروعك؟' : 'Need a free consultation for your project?'}
              </p>
              <Link href="/services" className="inline-flex items-center gap-2 bg-cyan-500 text-white px-6 py-2.5 rounded-lg font-semibold hover:bg-cyan-600 transition-colors text-sm">
                {locale === 'ar' ? 'تعرف على خدماتنا' : 'Explore Our Services'}
                <Rocket className="w-4 h-4" />
              </Link>
            </div>
          </div>
        </section>
      <section className="py-16"><div className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8"><div className="bg-gradient-to-br from-cyan-900/30 to-gray-900 border border-cyan-500/20 rounded-2xl p-8 lg:p-12"><div className="flex items-start gap-4 mb-6"><div className="w-14 h-14 bg-cyan-500/20 rounded-2xl flex items-center justify-center flex-shrink-0"><Rocket className="w-7 h-7 text-cyan-400" /></div><div><h2 className="text-3xl font-bold text-white mb-2">{c.digitalVision.title}</h2></div></div><p className="text-gray-300 leading-relaxed mb-8">{c.digitalVision.description}</p><div className="grid sm:grid-cols-2 gap-3">{c.digitalVision.features.map((f, i) => (<div key={i} className="flex items-start gap-3 bg-black/30 rounded-xl p-3"><CheckCircle className="w-5 h-5 text-cyan-500 flex-shrink-0 mt-0.5" /><span className="text-gray-300 text-sm">{f}</span></div>))}</div></div></div></section>
      <section className="py-16"><div className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8"><h2 className="text-3xl font-bold text-white mb-8 text-center flex items-center justify-center gap-3"><MapPin className="w-6 h-6 text-cyan-400" />{c.cities.title}</h2><div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-5 gap-4">{c.cities.list.map((city, i) => (<div key={i} className="bg-gray-900/60 border border-gray-800 rounded-xl p-4 text-center hover:border-cyan-500/50 transition-colors"><div className="text-white font-semibold mb-1">{city.name}</div><div className="text-gray-500 text-xs">{city.desc}</div></div>))}</div></div></section>
      <section className="py-16"><div className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8"><div className="text-center mb-12"><h2 className="text-3xl lg:text-4xl font-bold text-white mb-4">{c.sectors.title}</h2><p className="text-gray-400 text-lg">{c.sectors.subtitle}</p></div><div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-4">{c.sectors.list.map((s, i) => { const SI = s.icon; return (<div key={i} className="bg-gray-900/40 border border-gray-800 rounded-xl p-5 hover:border-cyan-500/40 transition-colors group"><div className="flex items-center gap-3 mb-2"><div className="w-10 h-10 bg-cyan-500/10 rounded-lg flex items-center justify-center group-hover:bg-cyan-500/20 transition-colors"><SI className="w-5 h-5 text-cyan-400" /></div><h3 className="text-white font-semibold">{s.name}</h3></div><p className="text-gray-500 text-sm">{s.desc}</p></div>); })}</div></div></section>
      <section className="py-16"><div className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8"><h2 className="text-3xl lg:text-4xl font-bold text-white mb-12 text-center">{c.whyUs.title}</h2><div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-5">{c.whyUs.reasons.map((r, i) => { const RI = r.icon; return (<div key={i} className="bg-gray-900/50 border border-gray-800 rounded-xl p-5 hover:border-cyan-500/40 transition-all duration-300"><div className="w-11 h-11 bg-cyan-500/15 rounded-xl flex items-center justify-center mb-4"><RI className="w-5 h-5 text-cyan-400" /></div><h3 className="text-white font-bold mb-2 text-sm">{r.title}</h3><p className="text-gray-500 text-xs leading-relaxed">{r.desc}</p></div>); })}</div></div></section>
      <section className="py-16"><div className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8"><div className="text-center mb-12"><h2 className="text-3xl lg:text-4xl font-bold text-white mb-4">{c.pricing.title}</h2><p className="text-gray-400 text-lg">{c.pricing.subtitle}</p></div><div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-5">{c.pricing.plans.map((p, i) => (<div key={i} className={`relative rounded-2xl p-6 transition-all duration-300 ${p.popular ? 'bg-cyan-900/30 border-2 border-cyan-500' : 'bg-gray-900/60 border border-gray-800 hover:border-gray-700'}`}>{p.popular && (<div className="absolute -top-3 left-1/2 transform -translate-x-1/2"><span className="bg-cyan-500 text-white text-xs font-bold px-3 py-1 rounded-full flex items-center gap-1"><Star className="w-3 h-3" />{locale === 'ar' ? 'الأكثر طلباً' : locale === 'fr' ? 'Populaire' : 'Popular'}</span></div>)}<h3 className="text-lg font-bold text-white mb-2 mt-2">{p.name}</h3><div className={`text-xl font-bold mb-5 ${p.popular ? 'text-cyan-400' : 'text-gray-300'}`}>{p.price}</div><ul className="space-y-2.5">{p.features.map((f, j) => (<li key={j} className="flex items-start gap-2 text-gray-400 text-sm"><CheckCircle className={`w-4 h-4 flex-shrink-0 mt-0.5 ${p.popular ? 'text-cyan-500' : 'text-gray-600'}`} />{f}</li>))}</ul></div>))}</div></div></section>
      <section className="py-16"><div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8"><h2 className="text-3xl font-bold text-white mb-10 text-center">{c.faq.title}</h2><div className="space-y-6">{c.faq.items.map((item, i) => (<div key={i} className="bg-gray-900/40 border border-gray-800 rounded-xl p-6"><h3 className="text-lg font-semibold text-white mb-3 flex items-start gap-3"><span className="text-cyan-400 font-bold text-xl leading-none mt-0.5">Q</span>{item.q}</h3><p className="text-gray-400 leading-relaxed pl-8">{item.a}</p></div>))}</div></div></section>
      <section className="py-16"><div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8"><div className="bg-gradient-to-r from-cyan-600 to-teal-500 rounded-2xl p-8 lg:p-12 text-center"><h2 className="text-3xl font-bold text-white mb-4">{c.cta.title}</h2><p className="text-cyan-100 text-lg mb-8 max-w-2xl mx-auto">{c.cta.subtitle}</p><div className="flex flex-col sm:flex-row items-center justify-center gap-4"><a href="https://wa.me/213549575512" target="_blank" rel="noopener noreferrer" className="inline-flex items-center gap-2 bg-white text-cyan-700 px-8 py-3 rounded-xl font-semibold hover:bg-cyan-50 transition-colors w-full sm:w-auto justify-center"><Phone className="w-5 h-5" />{c.cta.whatsapp}</a><a href={`mailto:${c.cta.emailAddr}`} className="inline-flex items-center gap-2 bg-cyan-700 text-white px-8 py-3 rounded-xl font-semibold hover:bg-cyan-800 transition-colors border border-cyan-400/30 w-full sm:w-auto justify-center"><Mail className="w-5 h-5" />{c.cta.email}</a></div><div className="mt-6 flex flex-wrap items-center justify-center gap-4 text-cyan-100 text-sm"><span className="flex items-center gap-1"><Phone className="w-4 h-4" />{c.cta.phone}</span><span className="flex items-center gap-1"><Mail className="w-4 h-4" />{c.cta.emailAddr}</span></div></div></div></section>
      <section className="py-16 border-t border-gray-800"><div className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8"><h2 className="text-2xl font-bold text-white mb-8">{c.related.title}</h2><div className="grid md:grid-cols-3 gap-5">{c.related.posts.map((post, i) => (<Link key={i} href={`/blog/${post.slug}`} className="bg-gray-900/50 border border-gray-800 rounded-xl p-5 hover:border-cyan-500/40 transition-colors group block"><h3 className="text-white font-semibold group-hover:text-cyan-400 transition-colors mb-2">{post.title}</h3><span className="text-cyan-500 text-sm flex items-center gap-1">{locale === 'ar' ? 'اقرأ المزيد' : locale === 'fr' ? 'Lire la suite' : 'Read more'}<ArrowLeft className={`w-3.5 h-3.5 ${isRTL ? '' : 'rotate-180'}`} /></span></Link>))}
            </div>

            <h3 className="text-lg font-semibold text-gray-400 mt-8 mb-4">
              {locale === 'ar' ? 'المزيد من خدماتنا في المنطقة' : 'More From Our Regional Coverage'}
            </h3>
            <div className="grid md:grid-cols-3 gap-5">
              <Link href="/blog/digital-transformation-saudi-arabia-vision-2030" className="bg-gray-900/50 border border-gray-800 rounded-xl p-5 hover:border-cyan-500/40 transition-colors group block">
                <h3 className="text-white font-semibold group-hover:text-cyan-400 transition-colors mb-2">
                  {locale === 'ar' ? 'التحول الرقمي في السعودية' : 'Digital Transformation in Saudi Arabia'}
                </h3>
                <span className="text-cyan-500 text-sm flex items-center gap-1">
                  {locale === 'ar' ? 'اقرأ المزيد' : 'Read more'}
                  <ArrowLeft className={`w-3.5 h-3.5 ${isRTL ? '' : 'rotate-180'}`} />
                </span>
              </Link>
              <Link href="/blog/artificial-intelligence-solutions-uae-2026" className="bg-gray-900/50 border border-gray-800 rounded-xl p-5 hover:border-cyan-500/40 transition-colors group block">
                <h3 className="text-white font-semibold group-hover:text-cyan-400 transition-colors mb-2">
                  {locale === 'ar' ? 'حلول الذكاء الاصطناعي في الإمارات' : 'AI Solutions in the UAE'}
                </h3>
                <span className="text-cyan-500 text-sm flex items-center gap-1">
                  {locale === 'ar' ? 'اقرأ المزيد' : 'Read more'}
                  <ArrowLeft className={`w-3.5 h-3.5 ${isRTL ? '' : 'rotate-180'}`} />
                </span>
              </Link>
              <Link href="/blog/mobile-app-development-kuwait-2026" className="bg-gray-900/50 border border-gray-800 rounded-xl p-5 hover:border-cyan-500/40 transition-colors group block">
                <h3 className="text-white font-semibold group-hover:text-cyan-400 transition-colors mb-2">
                  {locale === 'ar' ? 'تطوير التطبيقات في الكويت' : 'Mobile App Development in Kuwait'}
                </h3>
                <span className="text-cyan-500 text-sm flex items-center gap-1">
                  {locale === 'ar' ? 'اقرأ المزيد' : 'Read more'}
                  <ArrowLeft className={`w-3.5 h-3.5 ${isRTL ? '' : 'rotate-180'}`} />
                </span>
              </Link>
            </div>
          </div>
        </section>

      </article></>);
}
export async function getStaticProps({ locale }) { return { props: { ...(await serverSideTranslations(locale, ['common'])) } }; }
