import Image from 'next/image';import Link from 'next/link';import{motion}from'framer-motion';import{useRouter}from'next/router';import{serverSideTranslations}from'next-i18next/serverSideTranslations';import{ArrowRight,MessageCircle}from'lucide-react';import SEO from'../../components/SEO';
const W='https://wa.me/213549575512';
function R(t){return String(t).split(/(\*\*[^*]+\*\*)/g).map((p,i)=>p.startsWith('**')&&p.endsWith('**')?<span key={i} className="font-normal text-white border-b border-white/30">{p.slice(2,-2)}</span>:<span key={i}>{p}</span>);}
const f={hidden:{opacity:0,y:24},show:{opacity:1,y:0,transition:{duration:0.6,ease:[0.22,1,0.36,1]}}};
const st={hidden:{opacity:0},show:{opacity:1,transition:{staggerChildren:0.08,delayChildren:0.05}}};

const C={
  fr:{kind:'Guide fintech',title:"IA et fintech en Algérie — ce que les banques et les startups construisent vraiment en 2026.",dek:"La fintech algérienne est en train de rattraper 10 ans de retard en 2 ans. Voici les 6 cas d'usage IA qui se déploient réellement dans les banques et les fintechs du pays — pas ceux dont on parle en conférence, ceux qui tournent en production.",publishedAt:'Avril 2026',readTime:'11 min de lecture',author:'Symloop',
    intro:["L'Algérie a vécu en **18 mois** ce que la plupart des marchés fintech ont vécu en 5 ans. L'ouverture des paiements CIB et Edahabia au e-commerce, les premiers portefeuilles mobiles, les licences fintech de la Banque d'Algérie, la facturation électronique en cours de déploiement. **Le marché n'est plus « en retard » — il est en accélération.**","Et avec cette accélération, **l'intelligence artificielle entre dans la finance algérienne** par la porte opérationnelle, pas par la porte marketing. Les cas d'usage qui se déploient en production ne sont pas des chatbots — ce sont des systèmes qui touchent directement au flux d'argent."],
    sections:[
      {heading:'Le contexte : pourquoi maintenant',body:["Trois choses ont changé simultanément en Algérie. **Premièrement**, la Banque d'Algérie a ouvert les licences pour les établissements de paiement — de nouvelles fintechs naissent chaque trimestre. **Deuxièmement**, le volume de transactions CIB/Edahabia a explosé — les données existent enfin à un volume suffisant pour entraîner des modèles ML. **Troisièmement**, les banques publiques (BNA, BEA, BDL, CPA) lancent leur transformation digitale sous pression gouvernementale.","**Résultat : pour la première fois, il y a à la fois la demande, les données et les budgets** pour déployer de l'IA dans la finance algérienne. Pas dans 3 ans. Maintenant."]},
      {heading:'Cas 1 — Détection de fraude sur les transactions CIB/Edahabia',body:["C'est le cas d'usage #1 en production. Chaque banque algérienne traite **des millions de transactions par mois** via SATIM. Un modèle de détection d'anomalies entraîné sur l'historique transactionnel algérien identifie les **transactions suspectes en temps réel** : montants inhabituels, fréquence anormale, localisation incohérente, patterns de fraude connus dans la région MENA.","**Ce qui le rend spécifique à l'Algérie :** les patterns de fraude algériens ne sont pas les mêmes qu'en Europe. Les seuils CIB (200K DA) et Edahabia (100K DA), les comportements de paiement saisonniers (Ramadan, rentrée scolaire), et les spécificités du réseau SATIM nécessitent un modèle **entraîné localement, pas un modèle européen adapté**.","**Coût : 3–8M DA.** ROI en moins de 6 mois — la première fraude détectée paie généralement le projet."]},
      {heading:'Cas 2 — KYC automatisé et vérification d\'identité',body:["Chaque ouverture de compte bancaire ou fintech en Algérie nécessite une vérification d'identité (**KYC — Know Your Customer**). Aujourd'hui, c'est **un processus manuel de 3 à 5 jours** impliquant des photocopies, des vérifications visuelles et de la paperasse. Un système IA de KYC automatise : **lecture automatique de la carte d'identité nationale**, vérification de la photo, extraction des données, cross-check avec les bases de données.","**Gain :** l'ouverture de compte passe de **5 jours à 5 minutes**. Pour une fintech qui veut onboarder 10 000 clients en 3 mois, la différence entre un KYC manuel et un KYC IA est la différence entre réussir et mourir.","**Coût : 2–5M DA.** Particulièrement critique pour les nouvelles fintechs sous licence Banque d'Algérie."]},
      {heading:'Cas 3 — Scoring de crédit pour les non-bancarisés',body:["**60% de la population algérienne adulte n'a pas d'historique bancaire traditionnel.** Les modèles de scoring de crédit classiques (basés sur l'historique bancaire) ne fonctionnent tout simplement pas pour ces personnes. Un modèle de scoring alternatif utilise d'**autres signaux** : historique de paiement de factures (Algérie Télécom, Sonelgaz), comportement de recharge mobile, historique d'achats e-commerce via Edahabia.","**C'est le cas d'usage qui peut transformer le marché.** Si une fintech algérienne peut scorer les 60% de non-bancarisés de manière fiable, elle ouvre un marché de micro-crédit et de BNPL (Buy Now Pay Later) qui n'existe pas encore dans le pays.","**Coût : 5–12M DA.** Le modèle nécessite des partenariats data (télécoms, Algérie Poste) qui prennent du temps à négocier."]},
      {heading:'Cas 4 — Réconciliation automatique des paiements',body:["Chaque entreprise algérienne qui accepte le paiement CIB/Edahabia fait face au même cauchemar : **la réconciliation**. Le relevé SATIM ne matche pas toujours avec le système interne. Les doublons, les transactions en attente, les remboursements partiels, les timeouts — tout cela crée des écarts que quelqu'un doit résoudre manuellement.","Un système IA de réconciliation **matche automatiquement 95% des transactions** et signale les 5% restants comme exceptions à traiter manuellement. Pour une entreprise traitant **plus de 1000 transactions par mois**, c'est 2 à 3 jours de travail comptable économisés chaque mois.","**Coût : 1–3M DA.** L'un des ROI les plus rapides en fintech IA."]},
      {heading:'Cas 5 — Analyse de risque pour le crédit PME',body:["Les banques publiques algériennes **refusent 70% des demandes de crédit PME** — pas parce que les entreprises sont mauvaises, mais parce que l'analyse de risque est manuelle, lente, et basée sur des critères rigides hérités des années 1990. Un modèle IA d'analyse de risque PME ingère les **bilans, les flux de trésorerie, l'historique fiscal, les données CNRC, et le comportement bancaire** pour produire un score de risque en 48h au lieu de 3 mois.","**Impact potentiel :** si les banques publiques déployaient ce système, le taux d'acceptation des crédits PME pourrait passer de **30% à 50-60%** — ce qui injecterait des milliards de dinars dans l'économie algérienne.","**Coût : 8–20M DA.** C'est un projet de transformation qui nécessite l'adhésion du top management bancaire."]},
      {heading:'Cas 6 — Chatbot de service financier (le bon et le mauvais)',body:["**Le mauvais :** un chatbot GPT qui répond aux questions des clients sur leur solde, leurs transactions, leurs cartes. Ça semble bien en démo. En production, les erreurs sur des questions financières ont des conséquences juridiques. **Nous refusons ce type de projet.**","**Le bon :** un bot de routage intelligent qui lit la demande du client (en arabe dialectal, en français, ou en mélange des deux), **classe la demande par urgence et par type** (réclamation, information, opération), et la route vers le bon agent humain avec un résumé pré-rempli. L'agent humain prend la décision. Le bot fait le tri.","**Coût du bon : 1.5–3M DA.** Le mauvais coûte le même prix mais vous expose à un risque juridique. Choisissez le bon."]},
      {heading:'Ce que nous refusons de construire en fintech',body:["Nous livrons les 6 cas ci-dessus. Nous refusons systématiquement :","**Le trading algorithmique** — pas notre domaine, les risques sont trop spécifiques.","**Les systèmes de crédit autonomes** (sans validation humaine) — la régulation algérienne ne le permet pas encore, et les conséquences d'une erreur sont trop graves.","**Les crypto-wallets** — illégal en Algérie (pour l'instant).","**Les chatbots qui prennent des décisions financières** — comme expliqué ci-dessus.","Nous préférons perdre un deal que livrer un système qui expose notre client à un risque juridique ou réputationnel."]},
    ],
    pullQuote1:"Pour la première fois en Algérie, il y a à la fois la demande, les données et les budgets pour déployer de l'IA dans la finance. Pas dans 3 ans. Maintenant.",
    pullQuote2:"Si une fintech algérienne peut scorer les 60% de non-bancarisés de manière fiable, elle ouvre un marché qui n'existe pas encore dans le pays.",
    cta:{eyebrow:"Parlez à un ingénieur fintech",title:"Vous construisez un produit fintech en Algérie ou vous digitalisez une banque ? Décrivez votre projet en 5 minutes."},
    related:{insights:[{key:'ai',name:"Automatisation IA dans l'entreprise algérienne — 2026"},{key:'healthcare',name:"L'IA ne remplace pas les médecins. Elle remplace la paperasse."}],services:[{key:'ai',name:'Intelligence Artificielle'},{key:'software-engineering',name:'Ingénierie logicielle'}]},
  },
  en:{kind:'Fintech guide',title:'AI and fintech in Algeria — what banks and startups are actually building in 2026.',dek:"Algerian fintech is catching up on 10 years in 2 years. Here are the 6 AI use cases actually deploying in the country's banks and fintechs — not conference talk, production systems.",publishedAt:'April 2026',readTime:'11 min read',author:'Symloop',
    intro:["Algeria lived in **18 months** what most fintech markets lived in 5 years. CIB and Edahabia payments opened to e-commerce, first mobile wallets, Bank of Algeria fintech licenses, e-invoicing rolling out. **The market is no longer \"behind\" — it is accelerating.**","With this acceleration, **AI enters Algerian finance** through the operational door, not the marketing door. The use cases deploying in production are not chatbots — they are systems that directly touch the flow of money."],
    sections:[
      {heading:'The context: why now',body:["Three things changed simultaneously. **First**, Bank of Algeria opened payment institution licenses. **Second**, CIB/Edahabia transaction volume exploded — data finally exists at sufficient volume to train ML models. **Third**, public banks (BNA, BEA, BDL, CPA) are launching digital transformation under government pressure.","**Result: for the first time, there is demand, data, and budgets** to deploy AI in Algerian finance. Not in 3 years. Now."]},
      {heading:'Case 1 — Fraud detection on CIB/Edahabia transactions',body:["The #1 use case in production. An anomaly detection model trained on Algerian transaction history identifies **suspicious transactions in real time**. Algerian fraud patterns differ from European ones — CIB/Edahabia thresholds, seasonal payment behaviors (Ramadan, back-to-school), and SATIM network specifics require a **locally-trained model**.","**Cost: 3–8M DZD.** ROI in under 6 months — the first detected fraud typically pays for the project."]},
      {heading:'Case 2 — Automated KYC and identity verification',body:["Every bank/fintech account opening in Algeria requires KYC — currently **a 3-5 day manual process**. An AI KYC system automates: automatic national ID card reading, photo verification, data extraction, cross-check with databases.","**Result:** account opening goes from **5 days to 5 minutes**. Critical for new fintechs onboarding thousands of customers.","**Cost: 2–5M DZD.**"]},
      {heading:'Case 3 — Credit scoring for the unbanked',body:["**60% of Algerian adults have no traditional banking history.** Classic scoring models don't work. An alternative scoring model uses **other signals**: bill payment history (Algérie Télécom, Sonelgaz), mobile recharge behavior, Edahabia e-commerce history.","**This is the use case that can transform the market.** If a fintech can reliably score the 60% unbanked, it opens a micro-credit and BNPL market that doesn't exist yet.","**Cost: 5–12M DZD.** Requires data partnerships (telecoms, Algérie Poste)."]},
      {heading:'Case 4 — Automatic payment reconciliation',body:["Every Algerian company accepting CIB/Edahabia faces reconciliation nightmares. An AI system **auto-matches 95% of transactions** and flags the 5% as exceptions for manual review.","**Cost: 1–3M DZD.** One of the fastest ROI in fintech AI."]},
      {heading:'Case 5 — SME credit risk analysis',body:["Algerian public banks **reject 70% of SME credit applications** — not because businesses are bad, but because risk analysis is manual and rigid. An AI risk model ingests **financial statements, cash flows, tax history, CNRC data, and banking behavior** to produce a risk score in 48h instead of 3 months.","**Potential impact:** SME credit acceptance could go from **30% to 50-60%** — injecting billions of dinars into the Algerian economy.","**Cost: 8–20M DZD.** Transformation project requiring bank top management buy-in."]},
      {heading:'Case 6 — Financial service chatbot (the good and the bad)',body:["**The bad:** a GPT chatbot answering customer questions about balances and transactions. Errors on financial questions have legal consequences. **We refuse this type of project.**","**The good:** an intelligent routing bot that reads the customer request (Algerian Arabic, French, or mixed), **classifies by urgency and type**, and routes to the right human agent with a pre-filled summary. The human decides. The bot sorts.","**Cost of the good: 1.5–3M DZD.** The bad costs the same but exposes you to legal risk."]},
      {heading:'What we refuse to build in fintech',body:["We deliver the 6 cases above. We systematically refuse: **algorithmic trading**, **autonomous credit systems** (without human validation), **crypto wallets** (illegal in Algeria), **chatbots that make financial decisions**. We prefer losing a deal to delivering a system that exposes our client to legal or reputational risk."]},
    ],
    pullQuote1:"For the first time in Algeria, there is demand, data, and budgets to deploy AI in finance. Not in 3 years. Now.",
    pullQuote2:"If an Algerian fintech can reliably score the 60% unbanked, it opens a market that doesn't exist yet in the country.",
    cta:{eyebrow:'Talk to a fintech engineer',title:'Building a fintech product in Algeria or digitalizing a bank? Describe your project in 5 minutes.'},
    related:{insights:[{key:'ai',name:'AI automation in Algerian business — 2026'},{key:'healthcare',name:'AI is not replacing doctors. It is replacing the paperwork.'}],services:[{key:'ai',name:'Artificial Intelligence'},{key:'software-engineering',name:'Software Engineering'}]},
  },
  ar:{kind:'دليل فينتك',title:'الذكاء الاصطناعي والتكنولوجيا المالية في الجزائر — ما تبنيه البنوك والشركات الناشئة فعلاً في 2026.',dek:'التكنولوجيا المالية الجزائرية تلحق بـ10 سنوات في سنتين. إليك 6 حالات استخدام ذكاء اصطناعي تنتشر فعلاً في بنوك البلاد وشركات الفينتك.',publishedAt:'أبريل 2026',readTime:'11 دقيقة قراءة',author:'سيملوب',
    intro:['عاشت الجزائر في **18 شهراً** ما عاشته معظم أسواق الفينتك في 5 سنوات. فتح مدفوعات CIB والذهبية للتجارة الإلكترونية، أول المحافظ المحمولة، تراخيص الفينتك من بنك الجزائر. **السوق لم يعد "متأخراً" — إنه يتسارع.**','ومع هذا التسارع، **يدخل الذكاء الاصطناعي المالية الجزائرية** من الباب التشغيلي لا من باب التسويق. حالات الاستخدام التي تنتشر في الإنتاج ليست روبوتات محادثة — إنها أنظمة تمس مباشرة تدفق المال.'],
    sections:[
      {heading:'السياق: لماذا الآن',body:['ثلاثة أشياء تغيرت في وقت واحد. **أولاً**، بنك الجزائر فتح تراخيص مؤسسات الدفع. **ثانياً**، حجم معاملات CIB/الذهبية انفجر — البيانات موجودة أخيراً بحجم كافٍ لتدريب نماذج ML. **ثالثاً**، البنوك العامة تطلق تحولها الرقمي تحت ضغط حكومي.','**النتيجة: لأول مرة، هناك طلب وبيانات وميزانيات** لنشر الذكاء الاصطناعي في المالية الجزائرية. ليس في 3 سنوات. الآن.']},
      {heading:'الحالة 1 — كشف الاحتيال على معاملات CIB/الذهبية',body:['حالة الاستخدام #1 في الإنتاج. نموذج كشف شذوذ مدرَّب على التاريخ المعاملاتي الجزائري يحدد **المعاملات المشبوهة في الوقت الفعلي**. أنماط الاحتيال الجزائرية تختلف عن الأوروبية — حدود CIB (200K دج) والذهبية (100K دج)، السلوكيات الموسمية (رمضان، الدخول المدرسي).','**التكلفة: 3–8 مليون دج.** العائد في أقل من 6 أشهر.']},
      {heading:'الحالة 2 — KYC آلي والتحقق من الهوية',body:['كل فتح حساب بنكي أو فينتك في الجزائر يتطلب KYC — حالياً **عملية يدوية من 3 إلى 5 أيام**. نظام IA KYC يؤتمت: قراءة بطاقة الهوية الوطنية، التحقق من الصورة، استخراج البيانات.','**النتيجة:** فتح الحساب ينتقل من **5 أيام إلى 5 دقائق**.','**التكلفة: 2–5 مليون دج.**']},
      {heading:'الحالة 3 — تسجيل ائتماني لغير المتبنكين',body:['**60% من البالغين الجزائريين ليس لديهم تاريخ مصرفي تقليدي.** نموذج تسجيل بديل يستخدم **إشارات أخرى**: تاريخ دفع الفواتير (اتصالات الجزائر، سونلغاز)، سلوك شحن الموبايل، تاريخ مشتريات الذهبية.','**إذا استطاعت فينتك جزائرية تسجيل الـ60% غير المتبنكين بشكل موثوق، تفتح سوقاً لا يوجد بعد.**','**التكلفة: 5–12 مليون دج.**']},
      {heading:'الحالة 4 — تسوية تلقائية للمدفوعات',body:['نظام ذكاء اصطناعي يطابق تلقائياً **95% من المعاملات** ويشير إلى الـ5% المتبقية كاستثناءات للمراجعة اليدوية.','**التكلفة: 1–3 مليون دج.** من أسرع العوائد في فينتك الذكاء الاصطناعي.']},
      {heading:'الحالة 5 — تحليل مخاطر الائتمان للشركات الصغيرة والمتوسطة',body:['البنوك العامة الجزائرية **ترفض 70% من طلبات ائتمان الشركات الصغيرة** — ليس لأن الشركات سيئة، بل لأن تحليل المخاطر يدوي وجامد. نموذج IA يستوعب **البيانات المالية والتدفقات النقدية والتاريخ الضريبي وبيانات CNRC** لإنتاج درجة مخاطر في 48 ساعة بدلاً من 3 أشهر.','**التكلفة: 8–20 مليون دج.**']},
      {heading:'الحالة 6 — روبوت خدمة مالية (الجيد والسيء)',body:['**السيء:** روبوت GPT يجيب على أسئلة العملاء عن الأرصدة والمعاملات. الأخطاء في الأسئلة المالية لها عواقب قانونية. **نرفض هذا النوع.**','**الجيد:** روبوت توجيه ذكي يقرأ طلب العميل (بالدارجة، بالفرنسية، أو خليط)، **يصنف حسب الأولوية والنوع**، ويوجه إلى الوكيل البشري المناسب بملخص مسبق.','**تكلفة الجيد: 1.5–3 مليون دج.**']},
      {heading:'ما نرفض بناءه في الفينتك',body:['نسلّم الحالات الست أعلاه. نرفض منهجياً: **التداول الخوارزمي**، **أنظمة الائتمان المستقلة** (بدون تحقق بشري)، **محافظ العملات الرقمية** (غير قانونية في الجزائر)، **الروبوتات التي تتخذ قرارات مالية**. نفضل خسارة صفقة على تسليم نظام يعرض عملاءنا لمخاطر قانونية.']},
    ],
    pullQuote1:'لأول مرة في الجزائر، هناك طلب وبيانات وميزانيات لنشر الذكاء الاصطناعي في المالية. ليس في 3 سنوات. الآن.',
    pullQuote2:'إذا استطاعت فينتك جزائرية تسجيل الـ60% غير المتبنكين بشكل موثوق، تفتح سوقاً لا يوجد بعد في البلاد.',
    cta:{eyebrow:'تحدث مع مهندس فينتك',title:'تبني منتج فينتك في الجزائر أو ترقمن بنكاً؟ صف مشروعك في 5 دقائق.'},
    related:{insights:[{key:'ai',name:'أتمتة الذكاء الاصطناعي في الشركات الجزائرية — 2026'},{key:'healthcare',name:'الذكاء الاصطناعي لا يحل محل الأطباء. إنه يحل محل الأوراق.'}],services:[{key:'ai',name:'الذكاء الاصطناعي'},{key:'software-engineering',name:'هندسة البرمجيات'}]},
  },
};

export default function Page(){const{locale}=useRouter();const isRtl=locale==='ar';const c=C[locale]||C.fr;const ld={'@context':'https://schema.org','@type':'BlogPosting',headline:c.title,description:c.dek,image:['https://symloop.com/blog/cover-ai-fintech-algerie.jpg'],datePublished:'2026-04-14',author:{'@type':'Organization',name:'Symloop'},mainEntityOfPage:'https://symloop.com/blog/ia-fintech-banque-algerie-2026/'};const bc=[{name:'Home',url:'https://symloop.com/'},{name:'Blog',url:'https://symloop.com/blog/'},{name:c.title,url:'https://symloop.com/blog/ia-fintech-banque-algerie-2026/'}];
  return(<><SEO title={`${c.title} — Symloop`} description={c.dek} keywords="ia fintech algérie, intelligence artificielle banque algérie, fintech algérie 2026, détection fraude CIB edahabia, KYC automatisé algérie, scoring crédit algérie, paiement électronique algérie, ai fintech algeria, fraud detection algeria banking, credit scoring unbanked algeria" type="article" structuredData={ld} breadcrumbs={bc} image="/blog/cover-ai-fintech-algerie.jpg"/>
    <main dir={isRtl?'rtl':'ltr'} className="bg-black text-white">
      <section className="relative border-b border-white/[0.06]"><div className="max-w-5xl mx-auto px-6 lg:px-10 pt-32 lg:pt-40 pb-16"><motion.div initial="hidden" animate="show" variants={st}><motion.div variants={f} className="flex items-center gap-3 mb-8"><Link href="/blog/" className="font-mono text-[11px] tracking-[0.2em] uppercase text-white/40 hover:text-white transition-colors">{c.kind}</Link><span className="h-px w-12 bg-white/20"/><span className="font-mono text-[11px] tracking-[0.15em] uppercase text-white/35">{c.publishedAt}</span></motion.div><motion.h1 variants={f} className="text-4xl lg:text-6xl xl:text-7xl font-light tracking-tight leading-[1.05]">{c.title}</motion.h1><motion.p variants={f} className="mt-8 text-xl lg:text-2xl text-white/60 leading-relaxed font-light max-w-3xl">{c.dek}</motion.p><motion.div variants={f} className="mt-12 flex flex-wrap items-center gap-x-10 gap-y-3 font-mono text-[11px] tracking-[0.15em] uppercase text-white/35 pt-8 border-t border-white/[0.08]"><span>{c.author}</span><span>{c.readTime}</span></motion.div></motion.div></div><div className="relative w-full aspect-[16/9] lg:aspect-[21/9] border-y border-white/[0.06] bg-white/[0.02] overflow-hidden"><Image src="/blog/cover-ai-fintech-algerie.jpg" alt={c.title} fill priority sizes="100vw" className="object-cover"/></div></section>
      <article className="max-w-3xl mx-auto px-6 lg:px-10 py-20 lg:py-28"><motion.div initial="hidden" whileInView="show" viewport={{once:true,margin:'-100px'}} variants={st} className="space-y-7 mb-20">{c.intro.map((p,i)=><motion.p key={i} variants={f} className="text-xl lg:text-2xl text-white/80 leading-[1.55] font-light">{R(p)}</motion.p>)}</motion.div>
        {c.sections.map((s,idx)=>(<div key={idx}><motion.section initial="hidden" whileInView="show" viewport={{once:true,margin:'-100px'}} variants={st} className="mb-12 lg:mb-16"><motion.div variants={f} className="flex items-baseline gap-5 mb-6"><span className="font-mono text-xs tracking-[0.15em] text-white/30">{String(idx+1).padStart(2,'0')}</span><h2 className="text-2xl lg:text-4xl font-light tracking-tight text-white leading-[1.1]">{s.heading}</h2></motion.div><div className="space-y-5 ps-0 lg:ps-10">{s.body.map((p,i)=><motion.p key={i} variants={f} className="text-lg lg:text-xl text-white/70 leading-[1.65]">{R(p)}</motion.p>)}</div></motion.section>{idx===0&&c.pullQuote1&&<motion.figure initial={{opacity:0,y:30}} whileInView={{opacity:1,y:0}} viewport={{once:true}} transition={{duration:0.7}} className="my-20 lg:my-24 border-y border-white/[0.08] py-12 lg:py-16"><blockquote className="text-3xl lg:text-4xl xl:text-5xl font-light tracking-tight text-white leading-[1.15]">«{c.pullQuote1}»</blockquote></motion.figure>}{idx===3&&c.pullQuote2&&<motion.figure initial={{opacity:0,y:30}} whileInView={{opacity:1,y:0}} viewport={{once:true}} transition={{duration:0.7}} className="my-20 lg:my-24 border-y border-white/[0.08] py-12 lg:py-16"><blockquote className="text-3xl lg:text-4xl xl:text-5xl font-light tracking-tight text-white leading-[1.15]">«{c.pullQuote2}»</blockquote></motion.figure>}</div>))}</article>
      <section className="border-t border-white/[0.06]"><div className="max-w-7xl mx-auto px-6 lg:px-10 py-24 lg:py-32"><div className="grid grid-cols-1 lg:grid-cols-12 gap-12"><div className="lg:col-span-6"><div className="flex items-center gap-3 mb-8"><span className="font-mono text-[11px] tracking-[0.2em] uppercase text-white/40">{c.cta.eyebrow}</span><span className="h-px w-12 bg-white/20"/></div><h2 className="text-3xl lg:text-5xl font-light tracking-tight leading-[1.1] mb-10">{c.cta.title}</h2><div className="flex flex-wrap gap-4"><a href={W} target="_blank" rel="noopener noreferrer" className="group inline-flex items-center gap-3 bg-white text-black px-8 py-4 text-sm font-medium tracking-wide hover:bg-white/90 transition-colors"><MessageCircle className="w-4 h-4" strokeWidth={1.75}/><span>WhatsApp</span><ArrowRight className="w-4 h-4 transition-transform group-hover:translate-x-1" strokeWidth={1.75}/></a></div></div><div className="lg:col-span-6"><div className="font-mono text-[11px] tracking-[0.2em] uppercase text-white/40 mb-8">— Related</div><ul className="space-y-px bg-white/[0.06] border border-white/[0.06]">{c.related.insights.map(it=><li key={it.key} className="bg-black"><Link href={`/insights/${it.key}/`} className="group block p-6 transition-colors hover:bg-white/[0.025]"><div className="font-mono text-[10px] tracking-[0.2em] uppercase text-white/40 mb-2">Insight</div><h3 className="text-base font-light text-white leading-snug">{it.name}</h3></Link></li>)}{c.related.services.map(s=><li key={s.key} className="bg-black"><Link href={`/services/${s.key}/`} className="group block p-6 transition-colors hover:bg-white/[0.025]"><div className="font-mono text-[10px] tracking-[0.2em] uppercase text-white/40 mb-2">Service</div><h3 className="text-base font-light text-white leading-snug">{s.name}</h3></Link></li>)}</ul></div></div></div></section>
    </main></>);
}
export async function getStaticProps({locale}){return{props:{...(await serverSideTranslations(locale,['common']))}};}
