import Image from 'next/image';import Link from 'next/link';import{motion}from'framer-motion';import{useRouter}from'next/router';import{serverSideTranslations}from'next-i18next/serverSideTranslations';import{ArrowRight,MessageCircle}from'lucide-react';import SEO from'../../components/SEO';
const W='https://wa.me/213549575512';
function R(t){return String(t).split(/(\*\*[^*]+\*\*)/g).map((p,i)=>p.startsWith('**')&&p.endsWith('**')?<span key={i} className="font-normal text-white border-b border-white/30">{p.slice(2,-2)}</span>:<span key={i}>{p}</span>);}
const f={hidden:{opacity:0,y:24},show:{opacity:1,y:0,transition:{duration:0.6,ease:[0.22,1,0.36,1]}}};
const st={hidden:{opacity:0},show:{opacity:1,transition:{staggerChildren:0.08,delayChildren:0.05}}};

const C={
  fr:{kind:'Guide technique',title:'CIB, Edahabia, SATIM — guide d\'intégration technique pour entreprises algériennes.',dek:"Comment intégrer les paiements CIB et Edahabia dans votre application ou site web en Algérie. Architecture, flux, erreurs courantes, et les pièges que la documentation SATIM ne mentionne pas.",publishedAt:'Avril 2026',readTime:'12 min de lecture',author:'Symloop',
    intro:["Si vous développez une application ou un site e-commerce en Algérie, vous devez intégrer **CIB (Carte Interbancaire) et Edahabia (Algérie Poste)**. C'est obligatoire pour les paiements en ligne. Et c'est **l'intégration la plus mal documentée de tout l'écosystème tech algérien.** Ce guide est ce que nous aurions aimé avoir quand nous avons fait notre première intégration SATIM en 2020."],
    sections:[
      {heading:'CIB vs Edahabia — quelle différence ?',body:["**CIB (Carte Interbancaire)** est la carte bancaire classique émise par les banques algériennes (BNA, BEA, BDL, CPA, etc.). Gérée par le **réseau SATIM**. Environ **8 millions de cartes** en circulation. Utilisée principalement par les salariés et les fonctionnaires.","**Edahabia** est la carte prépayée d'Algérie Poste. Gérée aussi par **SATIM** mais via un réseau séparé. Environ **20 millions de cartes** — **la carte la plus répandue en Algérie**. Si vous ne supportez pas Edahabia, vous excluez 70% de vos clients potentiels.","**Les deux passent par SATIM** (Société d'Automatisation des Transactions Interbancaires et de Monétique). C'est le point d'entrée unique. Vous n'intégrez pas CIB et Edahabia séparément — vous intégrez **la passerelle SATIM** qui gère les deux."]},
      {heading:'Architecture d\'intégration — le flux complet',body:["Le flux standard SATIM est un **redirect flow** en 5 étapes :","**1.** Votre app envoie une requête POST à l'API SATIM avec : montant, devise (DZD), URL de retour, identifiant commande. **2.** SATIM redirige le client vers une page de paiement hébergée par SATIM (pas chez vous). **3.** Le client entre ses informations carte. **4.** SATIM traite le paiement et redirige vers votre URL de retour avec un code de résultat. **5.** Votre backend vérifie le code, confirme la commande, et affiche un reçu.","**Point critique :** ne faites JAMAIS confiance à la redirection seule. Utilisez toujours le **callback serveur-à-serveur (S2S)** pour confirmer le paiement côté backend. Des clients ferment leur navigateur avant la redirection — **sans le callback S2S, vous pensez que le paiement a échoué alors qu'il a réussi.**"]},
      {heading:'Les 5 pièges que la documentation ne mentionne pas',body:["**Piège 1 : Le sandbox SATIM est souvent hors service.** L'environnement de test tombe régulièrement. Gardez une journée de marge dans votre planning pour les périodes où le sandbox ne répond pas. **Testez le week-end — le sandbox est plus stable.**","**Piège 2 : Les codes d'erreur ne sont pas tous documentés.** Vous recevrez des codes qui n'apparaissent dans aucune documentation. **Loggez tout.** Envoyez les codes inconnus au support SATIM par email — ils répondent en 2 à 5 jours ouvrés.","**Piège 3 : Le callback S2S arrive parfois AVANT la redirection client.** Votre backend doit gérer cette race condition. **Utilisez un état « paiement en attente de confirmation » dans votre base de données**, pas un simple « payé / non payé ».","**Piège 4 : Edahabia et CIB ont des limites de transaction différentes.** CIB : **200 000 DA par transaction** (variable selon la banque). Edahabia : **100 000 DA par transaction** standard. Si votre panier dépasse ces montants, **le paiement sera refusé sans message d'erreur clair.**","**Piège 5 : Le certificat SSL de votre domaine doit être parfait.** SATIM vérifie le certificat de votre URL de retour. Un certificat auto-signé, expiré, ou mal configuré = **paiement qui aboutit mais callback qui n'arrive jamais**. Utilisez Let's Encrypt et vérifiez la chaîne de certification complète."]},
      {heading:'Stack technique recommandée',body:["Après 20+ intégrations SATIM livrées, voici notre stack recommandée :","**Backend :** Node.js (NestJS) ou Python (Django/FastAPI). Les deux ont des bibliothèques HTTP robustes pour gérer les appels SATIM. **Évitez PHP** pour les nouvelles intégrations — la gestion des callbacks asynchrones est plus fragile.","**Base de données :** PostgreSQL avec une table dédiée `payment_transactions` contenant : ID commande, montant, statut (pending/success/failed/callback_received), timestamp, code SATIM retourné. **Indexez sur le statut** — vous allez beaucoup querier les pending.","**File d'attente :** Redis ou Bull pour les jobs de vérification différée. Si le callback S2S n'arrive pas en 5 minutes, lancez un job de vérification manuelle via l'API SATIM.","**Monitoring :** Logguez chaque requête SATIM et chaque callback avec timestamps. **Quand un client dit « j'ai payé mais ma commande n'est pas confirmée », vous avez besoin de ces logs.** C'est le premier outil de debug."]},
      {heading:'Délai et coût réels d\'intégration',body:["**Si vous avez déjà un backend avec une base de données :** 3 à 6 semaines de développement, **300K–800K DA**. La majorité du temps est passée à gérer les edge cases (timeouts, doublons, race conditions) et à attendre les réponses du support SATIM.","**Si vous partez de zéro (nouveau site e-commerce) :** 8 à 12 semaines incluant le backend, **1.5–3M DA**. L'intégration SATIM elle-même est ~30% du travail. Le reste est le panier, les commandes, les emails transactionnels, le dashboard admin.","**Coût SATIM :** commission de **1.5 à 2.5%** par transaction (négociable selon le volume). Pas de frais mensuels fixes. Compte marchand à ouvrir auprès de votre banque + contrat SATIM (compter 2 à 4 semaines pour les formalités administratives)."]},
    ],
    pullQuote1:"Si vous ne supportez pas Edahabia, vous excluez 70% de vos clients potentiels en Algérie.",
    pullQuote2:"Ne faites JAMAIS confiance à la redirection seule. Le callback serveur-à-serveur est obligatoire.",
    cta:{eyebrow:'Parlez à un ingénieur',title:"Vous avez besoin d'intégrer CIB/Edahabia dans votre application ? Décrivez votre projet en 5 minutes."},
    related:{insights:[{key:'cost',name:'Le vrai coût du développement logiciel en Algérie'}],services:[{key:'software-engineering',name:'Ingénierie logicielle'},{key:'mobile',name:'Ingénierie Mobile'}]},
  },
  en:{kind:'Technical guide',title:'CIB, Edahabia, SATIM — integration guide for Algerian businesses.',dek:'How to integrate CIB and Edahabia payments into your app or website in Algeria. Architecture, flow, common errors, and the traps the SATIM documentation does not mention.',publishedAt:'April 2026',readTime:'12 min read',author:'Symloop',
    intro:["If you are building an app or e-commerce site in Algeria, you must integrate **CIB and Edahabia** payments via the **SATIM gateway**. It is **the worst-documented integration in the entire Algerian tech ecosystem.** This guide is what we wish we had when we did our first SATIM integration in 2020."],
    sections:[
      {heading:'CIB vs Edahabia — what is the difference?',body:["**CIB** is the standard bank card (~8 million cards). **Edahabia** is Algeria Post's prepaid card (~20 million cards — **the most common card in Algeria**). If you do not support Edahabia, you exclude 70% of potential customers.","**Both go through SATIM.** You integrate the SATIM gateway once, it handles both."]},
      {heading:'Integration architecture — the complete flow',body:["Standard SATIM is a **redirect flow** in 5 steps: 1. POST to SATIM API → 2. Client redirected to SATIM payment page → 3. Client enters card info → 4. SATIM redirects back with result code → 5. Backend verifies and confirms.","**Critical:** NEVER trust the redirect alone. Always use the **server-to-server (S2S) callback** to confirm payment backend-side. Clients close their browser before redirect — **without S2S callback, you think payment failed when it succeeded.**"]},
      {heading:'The 5 traps the documentation does not mention',body:["**Trap 1:** SATIM sandbox is often down. **Test on weekends — sandbox is more stable.**","**Trap 2:** Not all error codes are documented. **Log everything.** Send unknowns to SATIM support — they reply in 2-5 business days.","**Trap 3:** S2S callback sometimes arrives BEFORE client redirect. **Use a \"pending confirmation\" state in your database**, not just paid/unpaid.","**Trap 4:** CIB and Edahabia have different transaction limits. CIB: **200,000 DZD**. Edahabia: **100,000 DZD**. Exceeding = silent rejection.","**Trap 5:** Your SSL certificate must be perfect. SATIM verifies your return URL certificate. Self-signed or expired = **callback never arrives**."]},
      {heading:'Recommended tech stack',body:["**Backend:** Node.js (NestJS) or Python (Django/FastAPI). Avoid PHP for new integrations.","**Database:** PostgreSQL with dedicated `payment_transactions` table. Index on status.","**Queue:** Redis/Bull for deferred verification jobs if S2S callback does not arrive in 5 minutes.","**Monitoring:** Log every SATIM request and callback with timestamps."]},
      {heading:'Real timeline and cost',body:["**If you already have a backend:** 3-6 weeks, **300K–800K DZD**.","**From scratch (new e-commerce):** 8-12 weeks, **1.5–3M DZD**. SATIM integration is ~30% of the work.","**SATIM fees:** 1.5-2.5% commission per transaction. No monthly fixed fees. Merchant account + SATIM contract: 2-4 weeks for paperwork."]},
    ],
    pullQuote1:"If you do not support Edahabia, you exclude 70% of potential customers in Algeria.",
    pullQuote2:"NEVER trust the redirect alone. The server-to-server callback is mandatory.",
    cta:{eyebrow:'Talk to an engineer',title:"Need to integrate CIB/Edahabia into your application? Describe your project in 5 minutes."},
    related:{insights:[{key:'cost',name:'The real cost of building software in Algeria'}],services:[{key:'software-engineering',name:'Software Engineering'},{key:'mobile',name:'Mobile Engineering'}]},
  },
  ar:{kind:'دليل تقني',title:'CIB والذهبية وSATIM — دليل التكامل التقني للشركات الجزائرية.',dek:'كيف تدمج مدفوعات CIB والذهبية في تطبيقك أو موقعك الإلكتروني في الجزائر. الهندسة، التدفق، الأخطاء الشائعة، والفخاخ التي لا تذكرها وثائق SATIM.',publishedAt:'أبريل 2026',readTime:'12 دقيقة قراءة',author:'سيملوب',
    intro:['إذا كنت تبني تطبيقاً أو موقع تجارة إلكترونية في الجزائر، يجب أن تدمج **مدفوعات CIB والذهبية** عبر **بوابة SATIM**. إنها **أسوأ تكامل موثق في النظام التقني الجزائري بأكمله.** هذا الدليل هو ما تمنينا لو كان لدينا عندما أجرينا أول تكامل SATIM في 2020.'],
    sections:[
      {heading:'CIB مقابل الذهبية — ما الفرق؟',body:['**CIB** هي البطاقة البنكية (~8 مليون بطاقة). **الذهبية** هي بطاقة بريد الجزائر المدفوعة مسبقاً (~20 مليون بطاقة — **الأكثر انتشاراً في الجزائر**). إذا لم تدعم الذهبية، تستبعد 70% من العملاء المحتملين.','**كلاهما يمر عبر SATIM.** تدمج بوابة SATIM مرة واحدة، تتعامل مع الاثنين.']},
      {heading:'هندسة التكامل — التدفق الكامل',body:['تدفق SATIM القياسي هو **تدفق إعادة توجيه** في 5 خطوات.','**حرج:** لا تثق أبداً بإعادة التوجيه وحدها. استخدم دائماً **callback من الخادم إلى الخادم (S2S)** لتأكيد الدفع من جانب الخلفية.']},
      {heading:'الفخاخ الخمسة التي لا تذكرها الوثائق',body:['**فخ 1:** sandbox SATIM غالباً معطل. **اختبر في عطلة نهاية الأسبوع.**','**فخ 2:** ليست كل رموز الخطأ موثقة. **سجّل كل شيء.**','**فخ 3:** callback S2S أحياناً يصل قبل إعادة توجيه العميل. **استخدم حالة "في انتظار التأكيد" في قاعدة بياناتك.**','**فخ 4:** CIB والذهبية لها حدود معاملات مختلفة. CIB: **200,000 دج.** الذهبية: **100,000 دج.**','**فخ 5:** شهادة SSL لنطاقك يجب أن تكون مثالية.']},
      {heading:'المكدس التقني الموصى به',body:['**الخلفية:** Node.js (NestJS) أو Python (Django/FastAPI). تجنب PHP للتكاملات الجديدة.','**قاعدة البيانات:** PostgreSQL مع جدول مخصص `payment_transactions`.','**قائمة الانتظار:** Redis/Bull للتحقق المؤجل.']},
      {heading:'الجدول الزمني والتكلفة الحقيقية',body:['**إذا كان لديك خلفية بالفعل:** 3-6 أسابيع، **300K–800K دج**.','**من الصفر:** 8-12 أسبوعاً، **1.5–3M دج.**','**رسوم SATIM:** عمولة 1.5-2.5% لكل معاملة.']},
    ],
    pullQuote1:'إذا لم تدعم الذهبية، تستبعد 70% من العملاء المحتملين في الجزائر.',
    pullQuote2:'لا تثق أبداً بإعادة التوجيه وحدها. callback من الخادم إلى الخادم إلزامي.',
    cta:{eyebrow:'تحدث مع مهندس',title:'تحتاج دمج CIB/الذهبية في تطبيقك؟ صف مشروعك في 5 دقائق.'},
    related:{insights:[{key:'cost',name:'التكلفة الحقيقية لبناء البرمجيات في الجزائر'}],services:[{key:'software-engineering',name:'هندسة البرمجيات'},{key:'mobile',name:'هندسة الجوال'}]},
  },
};

export default function Page(){const{locale}=useRouter();const isRtl=locale==='ar';const c=C[locale]||C.fr;const ld={'@context':'https://schema.org','@type':'BlogPosting',headline:c.title,description:c.dek,image:['https://symloop.com/blog/cover-cib-edahabia-satim.jpg'],datePublished:'2026-04-12',author:{'@type':'Organization',name:'Symloop'},mainEntityOfPage:'https://symloop.com/blog/integration-cib-edahabia-satim-guide-technique-algerie-2026/'};const bc=[{name:'Home',url:'https://symloop.com/'},{name:'Blog',url:'https://symloop.com/blog/'},{name:c.title,url:'https://symloop.com/blog/integration-cib-edahabia-satim-guide-technique-algerie-2026/'}];
  return(<><SEO title={`${c.title} — Symloop`} description={c.dek} keywords="intégration CIB algérie, intégration edahabia, SATIM algérie, paiement en ligne algérie, gateway paiement algérie, CIB edahabia integration, SATIM payment gateway, e-commerce algérie paiement, algerian payment integration guide" type="article" structuredData={ld} breadcrumbs={bc} image="/blog/cover-cib-edahabia-satim.jpg"/>
    <main dir={isRtl?'rtl':'ltr'} className="bg-black text-white">
      <section className="relative border-b border-white/[0.06]"><div className="max-w-5xl mx-auto px-6 lg:px-10 pt-32 lg:pt-40 pb-16"><motion.div initial="hidden" animate="show" variants={st}><motion.div variants={f} className="flex items-center gap-3 mb-8"><Link href="/blog/" className="font-mono text-[11px] tracking-[0.2em] uppercase text-white/40 hover:text-white transition-colors">{c.kind}</Link><span className="h-px w-12 bg-white/20"/><span className="font-mono text-[11px] tracking-[0.15em] uppercase text-white/35">{c.publishedAt}</span></motion.div><motion.h1 variants={f} className="text-4xl lg:text-6xl xl:text-7xl font-light tracking-tight leading-[1.05]">{c.title}</motion.h1><motion.p variants={f} className="mt-8 text-xl lg:text-2xl text-white/60 leading-relaxed font-light max-w-3xl">{c.dek}</motion.p><motion.div variants={f} className="mt-12 flex flex-wrap items-center gap-x-10 gap-y-3 font-mono text-[11px] tracking-[0.15em] uppercase text-white/35 pt-8 border-t border-white/[0.08]"><span>{c.author}</span><span>{c.readTime}</span></motion.div></motion.div></div><div className="relative w-full aspect-[16/9] lg:aspect-[21/9] border-y border-white/[0.06] bg-white/[0.02] overflow-hidden"><Image src="/blog/cover-cib-edahabia-satim.jpg" alt={c.title} fill priority sizes="100vw" className="object-cover"/></div></section>
      <article className="max-w-3xl mx-auto px-6 lg:px-10 py-20 lg:py-28"><motion.div initial="hidden" whileInView="show" viewport={{once:true,margin:'-100px'}} variants={st} className="space-y-7 mb-20">{c.intro.map((p,i)=><motion.p key={i} variants={f} className="text-xl lg:text-2xl text-white/80 leading-[1.55] font-light">{R(p)}</motion.p>)}</motion.div>
        {c.sections.map((s,idx)=>(<div key={idx}><motion.section initial="hidden" whileInView="show" viewport={{once:true,margin:'-100px'}} variants={st} className="mb-12 lg:mb-16"><motion.div variants={f} className="flex items-baseline gap-5 mb-6"><span className="font-mono text-xs tracking-[0.15em] text-white/30">{String(idx+1).padStart(2,'0')}</span><h2 className="text-2xl lg:text-4xl font-light tracking-tight text-white leading-[1.1]">{s.heading}</h2></motion.div><div className="space-y-5 ps-0 lg:ps-10">{s.body.map((p,i)=><motion.p key={i} variants={f} className="text-lg lg:text-xl text-white/70 leading-[1.65]">{R(p)}</motion.p>)}</div></motion.section>{idx===0&&c.pullQuote1&&<motion.figure initial={{opacity:0,y:30}} whileInView={{opacity:1,y:0}} viewport={{once:true}} transition={{duration:0.7}} className="my-20 lg:my-24 border-y border-white/[0.08] py-12 lg:py-16"><blockquote className="text-3xl lg:text-4xl xl:text-5xl font-light tracking-tight text-white leading-[1.15]">«{c.pullQuote1}»</blockquote></motion.figure>}{idx===2&&c.pullQuote2&&<motion.figure initial={{opacity:0,y:30}} whileInView={{opacity:1,y:0}} viewport={{once:true}} transition={{duration:0.7}} className="my-20 lg:my-24 border-y border-white/[0.08] py-12 lg:py-16"><blockquote className="text-3xl lg:text-4xl xl:text-5xl font-light tracking-tight text-white leading-[1.15]">«{c.pullQuote2}»</blockquote></motion.figure>}</div>))}</article>
      <section className="border-t border-white/[0.06]"><div className="max-w-7xl mx-auto px-6 lg:px-10 py-24 lg:py-32"><div className="grid grid-cols-1 lg:grid-cols-12 gap-12"><div className="lg:col-span-6"><div className="flex items-center gap-3 mb-8"><span className="font-mono text-[11px] tracking-[0.2em] uppercase text-white/40">{c.cta.eyebrow}</span><span className="h-px w-12 bg-white/20"/></div><h2 className="text-3xl lg:text-5xl font-light tracking-tight leading-[1.1] mb-10">{c.cta.title}</h2><div className="flex flex-wrap gap-4"><a href={W} target="_blank" rel="noopener noreferrer" className="group inline-flex items-center gap-3 bg-white text-black px-8 py-4 text-sm font-medium tracking-wide hover:bg-white/90 transition-colors"><MessageCircle className="w-4 h-4" strokeWidth={1.75}/><span>WhatsApp</span><ArrowRight className="w-4 h-4 transition-transform group-hover:translate-x-1" strokeWidth={1.75}/></a></div></div><div className="lg:col-span-6"><div className="font-mono text-[11px] tracking-[0.2em] uppercase text-white/40 mb-8">— Related</div><ul className="space-y-px bg-white/[0.06] border border-white/[0.06]">{c.related.insights.map(it=><li key={it.key} className="bg-black"><Link href={`/insights/${it.key}/`} className="group block p-6 transition-colors hover:bg-white/[0.025]"><div className="font-mono text-[10px] tracking-[0.2em] uppercase text-white/40 mb-2">Insight</div><h3 className="text-base font-light text-white leading-snug">{it.name}</h3></Link></li>)}{c.related.services.map(s=><li key={s.key} className="bg-black"><Link href={`/services/${s.key}/`} className="group block p-6 transition-colors hover:bg-white/[0.025]"><div className="font-mono text-[10px] tracking-[0.2em] uppercase text-white/40 mb-2">Service</div><h3 className="text-base font-light text-white leading-snug">{s.name}</h3></Link></li>)}</ul></div></div></div></section>
    </main></>);
}
export async function getStaticProps({locale}){return{props:{...(await serverSideTranslations(locale,['common']))}};}
